"""empty message

Revision ID: 12ba67d8411a
Revises: 3dc621b3e1a6
Create Date: 2016-03-15 15:43:52.981805

"""

# revision identifiers, used by Alembic.
revision = '12ba67d8411a'
down_revision = '3dc621b3e1a6'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('result', sa.Column('profile_description', sa.String(length=250), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('result', 'profile_description')
    ### end Alembic commands ###
