"""empty message

Revision ID: 13e0ef2470c9
Revises: ad281ca21125
Create Date: 2016-03-14 16:14:30.434598

"""

# revision identifiers, used by Alembic.
revision = '13e0ef2470c9'
down_revision = 'ad281ca21125'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('patient', sa.Column('ethnicity', sa.String(length=250), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('patient', 'ethnicity')
    ### end Alembic commands ###
