"""empty message

Revision ID: 440bea99abd6
Revises: 716909215049
Create Date: 2016-04-06 13:33:56.292972

"""

# revision identifiers, used by Alembic.
revision = '440bea99abd6'
down_revision = '716909215049'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('outgoingmessage', sa.Column('count', sa.BigInteger(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('outgoingmessage', 'count')
    ### end Alembic commands ###
