"""empty message

Revision ID: 716909215049
Revises: d5ba70237f4e
Create Date: 2016-04-04 13:32:16.677317

"""

# revision identifiers, used by Alembic.
revision = '716909215049'
down_revision = 'd5ba70237f4e'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('outgoingmessage',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('updated', sa.DateTime(), nullable=True),
    sa.Column('created', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('outgoingmessage')
    ### end Alembic commands ###
