""" create subscription end point

Revision ID: a7d445896d4a
Revises: 12ba67d8411a
Create Date: 2016-03-18 11:14:40.057154

"""

# revision identifiers, used by Alembic.
revision = 'a7d445896d4a'
down_revision = '12ba67d8411a'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('subscription', sa.Column('end_point', sa.String(length=250), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('subscription', 'end_point')
    ### end Alembic commands ###
