"""empty message

Revision ID: ad281ca21125
Revises: 22156363ef5d
Create Date: 2016-03-14 15:56:32.868994

"""

# revision identifiers, used by Alembic.
revision = 'ad281ca21125'
down_revision = '22156363ef5d'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('patient', sa.Column('gp_practice_code', sa.String(length=20), nullable=True))
    op.add_column('patient', sa.Column('post_code', sa.String(length=20), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('patient', 'post_code')
    op.drop_column('patient', 'gp_practice_code')
    ### end Alembic commands ###
