"""empty message

Revision ID: b1af9829fc8d
Revises: f74b6ad81523
Create Date: 2016-05-06 14:34:12.328791

"""

# revision identifiers, used by Alembic.
revision = 'b1af9829fc8d'
down_revision = 'f74b6ad81523'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('allergy', 'allergy_type')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('allergy', sa.Column('allergy_type', sa.VARCHAR(length=250), autoincrement=False, nullable=True))
    ### end Alembic commands ###
