"""empty message

Revision ID: d5ba70237f4e
Revises: 27bcb4cd80c1
Create Date: 2016-03-30 09:37:10.536790

"""

# revision identifiers, used by Alembic.
revision = 'd5ba70237f4e'
down_revision = '27bcb4cd80c1'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        'inpatientadmission',
        'visit_number',
        new_column_name='external_identifier'
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        'inpatientadmission',
        'external_identifier',
        new_column_name='visit_number'
    )
    ### end Alembic commands ###
