import datetime

PATHOLOGY_DATA = [
    {u'Abnormal_Flag': u'',
    u'Accession_number': u'73151060487',
    u'DOB': datetime.datetime(1964, 1, 1, 0, 0),
    u'Date_Last_Obs_Normal': datetime.datetime(2015, 7, 18, 16, 25),
    u'Date_of_the_Observation': datetime.datetime(2015, 7, 18, 16, 26),
    u'Department': u'9',
    u'Encounter_Consultant_Code': u'C2754019',
    u'Encounter_Consultant_Name': u'DR. M. BERELOWITZ',
    u'Encounter_Consultant_Type': u'',
    u'Encounter_Location_Code': u'6N',
    u'Encounter_Location_Name': u'RAL 6 NORTH',
    u'Encounter_Location_Type': u'IP',
    u'Event_Date': datetime.datetime(2015, 7, 18, 16, 47),
    u'Firstname': u'TEST',
    u'MSH_Control_ID': u'18498139',
    u'OBR-5_Priority': u'N',
    u'OBR_Sequence_ID': u'2',
    u'OBR_Status': u'F',
    u'OBR_exam_code_ID': u'ANNR',
    u'OBR_exam_code_Text': u'ANTI NEURONAL AB REFERRAL',
    u'OBX_Sequence_ID': u'5',
    u'OBX_Status': u'F',
    u'OBX_exam_code_ID': u'AN5',
    u'OBX_exam_code_Text': u'Brain homogenate Western blot',
    u'OBX_id': 20334305,
    u'ORC-9_Datetime_of_Transaction': datetime.datetime(2015, 7, 18, 16, 47),
    u'Observation_date': datetime.datetime(2015, 7, 18, 16, 18),
    u'Order_Number': u'',
    u'Patient_Class': u'NHS',
    u'Patient_ID_External': u'7060976728',
    u'Patient_Number': u'20552710',
    u'Relevant_Clinical_Info': u'testing',
    u'Reported_date': datetime.datetime(2015, 7, 18, 16, 26),
    u'Request_Date': datetime.datetime(2015, 7, 18, 16, 15),
    u'Requesting_Clinician': u'C4369059_Chee Ronnie',
    u'Result_ID': u'0013I245895',
    u'Result_Range': u' -',
    u'Result_Units': u'',
    u'Result_Value': u'Negative',
    u'SEX': u'F',
    u'Specimen_Site': u'^&                              ^',
    u'Surname': u'ZZZTEST',
    u'Visit_Number': u'',
    u'crs_patient_masterfile_id': None,
    u'date_inserted': datetime.datetime(2015, 7, 18, 17, 0, 2, 240000),
    u'id': 5949264,
    u'last_updated': datetime.datetime(2015, 7, 18, 17, 0, 2, 240000),
    u'visible': u'Y'},
    {u'Abnormal_Flag': u'',
    u'Accession_number': u'73151060487',
    u'DOB': datetime.datetime(1964, 1, 1, 0, 0),
    u'Date_Last_Obs_Normal': datetime.datetime(2015, 7, 18, 16, 25),
    u'Date_of_the_Observation': datetime.datetime(2015, 7, 18, 16, 26),
    u'Department': u'9',
    u'Encounter_Consultant_Code': u'C2754019',
    u'Encounter_Consultant_Name': u'DR. M. BERELOWITZ',
    u'Encounter_Consultant_Type': u'',
    u'Encounter_Location_Code': u'6N',
    u'Encounter_Location_Name': u'RAL 6 NORTH',
    u'Encounter_Location_Type': u'IP',
    u'Event_Date': datetime.datetime(2015, 7, 18, 16, 47),
    u'Firstname': u'TEST',
    u'MSH_Control_ID': u'18498139',
    u'OBR-5_Priority': u'N',
    u'OBR_Sequence_ID': u'2',
    u'OBR_Status': u'F',
    u'OBR_exam_code_ID': u'ANNR',
    u'OBR_exam_code_Text': u'ANTI NEURONAL AB REFERRAL',
    u'OBX_Sequence_ID': u'6',
    u'OBX_Status': u'F',
    u'OBX_exam_code_ID': u'AN7',
    u'OBX_exam_code_Text': u'Anti-Hu antibodies',
    u'OBX_id': 20334306,
    u'ORC-9_Datetime_of_Transaction': datetime.datetime(2015, 7, 18, 16, 47),
    u'Observation_date': datetime.datetime(2015, 7, 18, 16, 18),
    u'Order_Number': u'',
    u'Patient_Class': u'NHS',
    u'Patient_ID_External': u'7060976728',
    u'Patient_Number': u'20552710',
    u'Relevant_Clinical_Info': u'testing',
    u'Reported_date': datetime.datetime(2015, 7, 18, 16, 26),
    u'Request_Date': datetime.datetime(2015, 7, 18, 16, 15),
    u'Requesting_Clinician': u'C4369059_Chee Ronnie',
    u'Result_ID': u'0013I245895',
    u'Result_Range': u' -',
    u'Result_Units': u'',
    u'Result_Value': u'Negative',
    u'SEX': u'F',
    u'Specimen_Site': u'^&                              ^',
    u'Surname': u'ZZZTEST',
    u'Visit_Number': u'',
    u'crs_patient_masterfile_id': None,
    u'date_inserted': datetime.datetime(2015, 7, 18, 17, 0, 2, 240000),
    u'id': 5949264,
    u'last_updated': datetime.datetime(2015, 7, 18, 17, 0, 2, 240000),
    u'visible': u'Y'},
    {u'Abnormal_Flag': u'',
    u'Accession_number': u'73151060487',
    u'DOB': datetime.datetime(1964, 1, 1, 0, 0),
    u'Date_Last_Obs_Normal': datetime.datetime(2015, 7, 18, 16, 26),
    u'Date_of_the_Observation': datetime.datetime(2015, 7, 18, 16, 26),
    u'Department': u'9',
    u'Encounter_Consultant_Code': u'C2754019',
    u'Encounter_Consultant_Name': u'DR. M. BERELOWITZ',
    u'Encounter_Consultant_Type': u'',
    u'Encounter_Location_Code': u'6N',
    u'Encounter_Location_Name': u'RAL 6 NORTH',
    u'Encounter_Location_Type': u'IP',
    u'Event_Date': datetime.datetime(2015, 7, 18, 16, 47),
    u'Firstname': u'TEST',
    u'MSH_Control_ID': u'18498139',
    u'OBR-5_Priority': u'N',
    u'OBR_Sequence_ID': u'2',
    u'OBR_Status': u'F',
    u'OBR_exam_code_ID': u'ANNR',
    u'OBR_exam_code_Text': u'ANTI NEURONAL AB REFERRAL',
    u'OBX_Sequence_ID': u'7',
    u'OBX_Status': u'F',
    u'OBX_exam_code_ID': u'AN8',
    u'OBX_exam_code_Text': u'Anti-Yo antibodies',
    u'OBX_id': 20334307,
    u'ORC-9_Datetime_of_Transaction': datetime.datetime(2015, 7, 18, 16, 47),
    u'Observation_date': datetime.datetime(2015, 7, 18, 16, 18),
    u'Order_Number': u'',
    u'Patient_Class': u'NHS',
    u'Patient_ID_External': u'7060976728',
    u'Patient_Number': u'20552710',
    u'Relevant_Clinical_Info': u'testing',
    u'Reported_date': datetime.datetime(2015, 7, 18, 16, 26),
    u'Request_Date': datetime.datetime(2015, 7, 18, 16, 15),
    u'Requesting_Clinician': u'C4369059_Chee Ronnie',
    u'Result_ID': u'0013I245895',
    u'Result_Range': u' -',
    u'Result_Units': u'',
    u'Result_Value': u'Negative',
    u'SEX': u'F',
    u'Specimen_Site': u'^&                              ^',
    u'Surname': u'ZZZTEST',
    u'Visit_Number': u'',
    u'crs_patient_masterfile_id': None,
    u'date_inserted': datetime.datetime(2015, 7, 18, 17, 0, 2, 240000),
    u'id': 5949264,
    u'last_updated': datetime.datetime(2015, 7, 18, 17, 0, 2, 240000),
    u'visible': u'Y'},
    {u'Abnormal_Flag': u'',
    u'Accession_number': u'73151060487',
    u'DOB': datetime.datetime(1964, 1, 1, 0, 0),
    u'Date_Last_Obs_Normal': datetime.datetime(2015, 7, 18, 16, 26),
    u'Date_of_the_Observation': datetime.datetime(2015, 7, 18, 16, 26),
    u'Department': u'9',
    u'Encounter_Consultant_Code': u'C2754019',
    u'Encounter_Consultant_Name': u'DR. M. BERELOWITZ',
    u'Encounter_Consultant_Type': u'',
    u'Encounter_Location_Code': u'6N',
    u'Encounter_Location_Name': u'RAL 6 NORTH',
    u'Encounter_Location_Type': u'IP',
    u'Event_Date': datetime.datetime(2015, 7, 18, 16, 47),
    u'Firstname': u'TEST',
    u'MSH_Control_ID': u'18498139',
    u'OBR-5_Priority': u'N',
    u'OBR_Sequence_ID': u'2',
    u'OBR_Status': u'F',
    u'OBR_exam_code_ID': u'ANNR',
    u'OBR_exam_code_Text': u'ANTI NEURONAL AB REFERRAL',
    u'OBX_Sequence_ID': u'8',
    u'OBX_Status': u'F',
    u'OBX_exam_code_ID': u'AN9',
    u'OBX_exam_code_Text': u'Anti-Ri antibodies',
    u'OBX_id': 20334308,
    u'ORC-9_Datetime_of_Transaction': datetime.datetime(2015, 7, 18, 16, 47),
    u'Observation_date': datetime.datetime(2015, 7, 18, 16, 18),
    u'Order_Number': u'',
    u'Patient_Class': u'NHS',
    u'Patient_ID_External': u'7060976728',
    u'Patient_Number': u'20552710',
    u'Relevant_Clinical_Info': u'testing',
    u'Reported_date': datetime.datetime(2015, 7, 18, 16, 26),
    u'Request_Date': datetime.datetime(2015, 7, 18, 16, 15),
    u'Requesting_Clinician': u'C4369059_Chee Ronnie',
    u'Result_ID': u'0013I245895',
    u'Result_Range': u' -',
    u'Result_Units': u'',
    u'Result_Value': u'Negative',
    u'SEX': u'F',
    u'Specimen_Site': u'^&                              ^',
    u'Surname': u'ZZZTEST',
    u'Visit_Number': u'',
    u'crs_patient_masterfile_id': None,
    u'date_inserted': datetime.datetime(2015, 7, 18, 17, 0, 2, 240000),
    u'id': 5949264,
    u'last_updated': datetime.datetime(2015, 7, 18, 17, 0, 2, 240000),
    u'visible': u'Y'},
    {u'Abnormal_Flag': u'',
    u'Accession_number': u'73151060487',
    u'DOB': datetime.datetime(1964, 1, 1, 0, 0),
    u'Date_Last_Obs_Normal': datetime.datetime(2015, 7, 18, 16, 26),
    u'Date_of_the_Observation': datetime.datetime(2015, 7, 18, 16, 26),
    u'Department': u'9',
    u'Encounter_Consultant_Code': u'C2754019',
    u'Encounter_Consultant_Name': u'DR. M. BERELOWITZ',
    u'Encounter_Consultant_Type': u'',
    u'Encounter_Location_Code': u'6N',
    u'Encounter_Location_Name': u'RAL 6 NORTH',
    u'Encounter_Location_Type': u'IP',
    u'Event_Date': datetime.datetime(2015, 7, 18, 16, 47),
    u'Firstname': u'TEST',
    u'MSH_Control_ID': u'18498139',
    u'OBR-5_Priority': u'N',
    u'OBR_Sequence_ID': u'2',
    u'OBR_Status': u'F',
    u'OBR_exam_code_ID': u'ANNR',
    u'OBR_exam_code_Text': u'ANTI NEURONAL AB REFERRAL',
    u'OBX_Sequence_ID': u'9',
    u'OBX_Status': u'F',
    u'OBX_exam_code_ID': u'AN10',
    u'OBX_exam_code_Text': u'Anti-Ma-1 antibodie',
    u'OBX_id': 20334309,
    u'ORC-9_Datetime_of_Transaction': datetime.datetime(2015, 7, 18, 16, 47),
    u'Observation_date': datetime.datetime(2015, 7, 18, 16, 18),
    u'Order_Number': u'',
    u'Patient_Class': u'NHS',
    u'Patient_ID_External': u'7060976728',
    u'Patient_Number': u'20552710',
    u'Relevant_Clinical_Info': u'testing',
    u'Reported_date': datetime.datetime(2015, 7, 18, 16, 26),
    u'Request_Date': datetime.datetime(2015, 7, 18, 16, 15),
    u'Requesting_Clinician': u'C4369059_Chee Ronnie',
    u'Result_ID': u'0013I245895',
    u'Result_Range': u' -',
    u'Result_Units': u'',
    u'Result_Value': u'Negative',
    u'SEX': u'F',
    u'Specimen_Site': u'^&                              ^',
    u'Surname': u'ZZZTEST',
    u'Visit_Number': u'',
    u'crs_patient_masterfile_id': None,
    u'date_inserted': datetime.datetime(2015, 7, 18, 17, 0, 2, 240000),
    u'id': 5949264,
    u'last_updated': datetime.datetime(2015, 7, 18, 17, 0, 2, 240000),
    u'visible': u'Y'},
    {u'Abnormal_Flag': u'',
    u'Accession_number': u'73151060487',
    u'DOB': datetime.datetime(1964, 1, 1, 0, 0),
    u'Date_Last_Obs_Normal': datetime.datetime(2015, 7, 18, 16, 26),
    u'Date_of_the_Observation': datetime.datetime(2015, 7, 18, 16, 26),
    u'Department': u'9',
    u'Encounter_Consultant_Code': u'C2754019',
    u'Encounter_Consultant_Name': u'DR. M. BERELOWITZ',
    u'Encounter_Consultant_Type': u'',
    u'Encounter_Location_Code': u'6N',
    u'Encounter_Location_Name': u'RAL 6 NORTH',
    u'Encounter_Location_Type': u'IP',
    u'Event_Date': datetime.datetime(2015, 7, 18, 16, 47),
    u'Firstname': u'TEST',
    u'MSH_Control_ID': u'18498139',
    u'OBR-5_Priority': u'N',
    u'OBR_Sequence_ID': u'2',
    u'OBR_Status': u'F',
    u'OBR_exam_code_ID': u'ANNR',
    u'OBR_exam_code_Text': u'ANTI NEURONAL AB REFERRAL',
    u'OBX_Sequence_ID': u'10',
    u'OBX_Status': u'F',
    u'OBX_exam_code_ID': u'AN11',
    u'OBX_exam_code_Text': u'Anti-Ma-2 antibodies',
    u'OBX_id': 20334310,
    u'ORC-9_Datetime_of_Transaction': datetime.datetime(2015, 7, 18, 16, 47),
    u'Observation_date': datetime.datetime(2015, 7, 18, 16, 18),
    u'Order_Number': u'',
    u'Patient_Class': u'NHS',
    u'Patient_ID_External': u'7060976728',
    u'Patient_Number': u'20552710',
    u'Relevant_Clinical_Info': u'testing',
    u'Reported_date': datetime.datetime(2015, 7, 18, 16, 26),
    u'Request_Date': datetime.datetime(2015, 7, 18, 16, 15),
    u'Requesting_Clinician': u'C4369059_Chee Ronnie',
    u'Result_ID': u'0013I245895',
    u'Result_Range': u' -',
    u'Result_Units': u'',
    u'Result_Value': u'Negative',
    u'SEX': u'F',
    u'Specimen_Site': u'^&                              ^',
    u'Surname': u'ZZZTEST',
    u'Visit_Number': u'',
    u'crs_patient_masterfile_id': None,
    u'date_inserted': datetime.datetime(2015, 7, 18, 17, 0, 2, 240000),
    u'id': 5949264,
    u'last_updated': datetime.datetime(2015, 7, 18, 17, 0, 2, 240000),
    u'visible': u'Y'},
    {u'Abnormal_Flag': u'',
    u'Accession_number': u'73151060487',
    u'DOB': datetime.datetime(1964, 1, 1, 0, 0),
    u'Date_Last_Obs_Normal': datetime.datetime(2015, 7, 18, 16, 26),
    u'Date_of_the_Observation': datetime.datetime(2015, 7, 18, 16, 26),
    u'Department': u'9',
    u'Encounter_Consultant_Code': u'C2754019',
    u'Encounter_Consultant_Name': u'DR. M. BERELOWITZ',
    u'Encounter_Consultant_Type': u'',
    u'Encounter_Location_Code': u'6N',
    u'Encounter_Location_Name': u'RAL 6 NORTH',
    u'Encounter_Location_Type': u'IP',
    u'Event_Date': datetime.datetime(2015, 7, 18, 16, 47),
    u'Firstname': u'TEST',
    u'MSH_Control_ID': u'18498139',
    u'OBR-5_Priority': u'N',
    u'OBR_Sequence_ID': u'2',
    u'OBR_Status': u'F',
    u'OBR_exam_code_ID': u'ANNR',
    u'OBR_exam_code_Text': u'ANTI NEURONAL AB REFERRAL',
    u'OBX_Sequence_ID': u'11',
    u'OBX_Status': u'F',
    u'OBX_exam_code_ID': u'AN12',
    u'OBX_exam_code_Text': u'Anti-CV2 (CRMP-5) antibodies',
    u'OBX_id': 20334311,
    u'ORC-9_Datetime_of_Transaction': datetime.datetime(2015, 7, 18, 16, 47),
    u'Observation_date': datetime.datetime(2015, 7, 18, 16, 18),
    u'Order_Number': u'',
    u'Patient_Class': u'NHS',
    u'Patient_ID_External': u'7060976728',
    u'Patient_Number': u'20552710',
    u'Relevant_Clinical_Info': u'testing',
    u'Reported_date': datetime.datetime(2015, 7, 18, 16, 26),
    u'Request_Date': datetime.datetime(2015, 7, 18, 16, 15),
    u'Requesting_Clinician': u'C4369059_Chee Ronnie',
    u'Result_ID': u'0013I245895',
    u'Result_Range': u' -',
    u'Result_Units': u'',
    u'Result_Value': u'Negative',
    u'SEX': u'F',
    u'Specimen_Site': u'^&                              ^',
    u'Surname': u'ZZZTEST',
    u'Visit_Number': u'',
    u'crs_patient_masterfile_id': None,
    u'date_inserted': datetime.datetime(2015, 7, 18, 17, 0, 2, 240000),
    u'id': 5949264,
    u'last_updated': datetime.datetime(2015, 7, 18, 17, 0, 2, 240000),
    u'visible': u'Y'},
    {u'Abnormal_Flag': u'',
    u'Accession_number': u'73151060487',
    u'DOB': datetime.datetime(1964, 1, 1, 0, 0),
    u'Date_Last_Obs_Normal': datetime.datetime(2015, 7, 18, 16, 26),
    u'Date_of_the_Observation': datetime.datetime(2015, 7, 18, 16, 26),
    u'Department': u'9',
    u'Encounter_Consultant_Code': u'C2754019',
    u'Encounter_Consultant_Name': u'DR. M. BERELOWITZ',
    u'Encounter_Consultant_Type': u'',
    u'Encounter_Location_Code': u'6N',
    u'Encounter_Location_Name': u'RAL 6 NORTH',
    u'Encounter_Location_Type': u'IP',
    u'Event_Date': datetime.datetime(2015, 7, 18, 16, 47),
    u'Firstname': u'TEST',
    u'MSH_Control_ID': u'18498139',
    u'OBR-5_Priority': u'N',
    u'OBR_Sequence_ID': u'2',
    u'OBR_Status': u'F',
    u'OBR_exam_code_ID': u'ANNR',
    u'OBR_exam_code_Text': u'ANTI NEURONAL AB REFERRAL',
    u'OBX_Sequence_ID': u'12',
    u'OBX_Status': u'F',
    u'OBX_exam_code_ID': u'AN13',
    u'OBX_exam_code_Text': u'Anti-Amphiphysin antibodies',
    u'OBX_id': 20334312,
    u'ORC-9_Datetime_of_Transaction': datetime.datetime(2015, 7, 18, 16, 47),
    u'Observation_date': datetime.datetime(2015, 7, 18, 16, 18),
    u'Order_Number': u'',
    u'Patient_Class': u'NHS',
    u'Patient_ID_External': u'7060976728',
    u'Patient_Number': u'20552710',
    u'Relevant_Clinical_Info': u'testing',
    u'Reported_date': datetime.datetime(2015, 7, 18, 16, 26),
    u'Request_Date': datetime.datetime(2015, 7, 18, 16, 15),
    u'Requesting_Clinician': u'C4369059_Chee Ronnie',
    u'Result_ID': u'0013I245895',
    u'Result_Range': u' -',
    u'Result_Units': u'',
    u'Result_Value': u'Negative',
    u'SEX': u'F',
    u'Specimen_Site': u'^&                              ^',
    u'Surname': u'ZZZTEST',
    u'Visit_Number': u'',
    u'crs_patient_masterfile_id': None,
    u'date_inserted': datetime.datetime(2015, 7, 18, 17, 0, 2, 240000),
    u'id': 5949264,
    u'last_updated': datetime.datetime(2015, 7, 18, 17, 0, 2, 240000),
    u'visible': u'Y'},
    {u'Abnormal_Flag': u'',
    u'Accession_number': u'73151060487',
    u'DOB': datetime.datetime(1964, 1, 1, 0, 0),
    u'Date_Last_Obs_Normal': datetime.datetime(2015, 7, 18, 16, 26),
    u'Date_of_the_Observation': datetime.datetime(2015, 7, 18, 16, 26),
    u'Department': u'9',
    u'Encounter_Consultant_Code': u'C2754019',
    u'Encounter_Consultant_Name': u'DR. M. BERELOWITZ',
    u'Encounter_Consultant_Type': u'',
    u'Encounter_Location_Code': u'6N',
    u'Encounter_Location_Name': u'RAL 6 NORTH',
    u'Encounter_Location_Type': u'IP',
    u'Event_Date': datetime.datetime(2015, 7, 18, 16, 47),
    u'Firstname': u'TEST',
    u'MSH_Control_ID': u'18498139',
    u'OBR-5_Priority': u'N',
    u'OBR_Sequence_ID': u'2',
    u'OBR_Status': u'F',
    u'OBR_exam_code_ID': u'ANNR',
    u'OBR_exam_code_Text': u'ANTI NEURONAL AB REFERRAL',
    u'OBX_Sequence_ID': u'13',
    u'OBX_Status': u'F',
    u'OBX_exam_code_ID': u'AN14',
    u'OBX_exam_code_Text': u'Anti-Sox 1 antibodies',
    u'OBX_id': 20334313,
    u'ORC-9_Datetime_of_Transaction': datetime.datetime(2015, 7, 18, 16, 47),
    u'Observation_date': datetime.datetime(2015, 7, 18, 16, 18),
    u'Order_Number': u'',
    u'Patient_Class': u'NHS',
    u'Patient_ID_External': u'7060976728',
    u'Patient_Number': u'20552710',
    u'Relevant_Clinical_Info': u'testing',
    u'Reported_date': datetime.datetime(2015, 7, 18, 16, 26),
    u'Request_Date': datetime.datetime(2015, 7, 18, 16, 15),
    u'Requesting_Clinician': u'C4369059_Chee Ronnie',
    u'Result_ID': u'0013I245895',
    u'Result_Range': u' -',
    u'Result_Units': u'',
    u'Result_Value': u'Negative',
    u'SEX': u'F',
    u'Specimen_Site': u'^&                              ^',
    u'Surname': u'ZZZTEST',
    u'Visit_Number': u'',
    u'crs_patient_masterfile_id': None,
    u'date_inserted': datetime.datetime(2015, 7, 18, 17, 0, 2, 240000),
    u'id': 5949264,
    u'last_updated': datetime.datetime(2015, 7, 18, 17, 0, 2, 240000),
    u'visible': u'Y'},
    {u'Abnormal_Flag': u'',
    u'Accession_number': u'73151060487',
    u'DOB': datetime.datetime(1964, 1, 1, 0, 0),
    u'Date_Last_Obs_Normal': datetime.datetime(2015, 7, 18, 16, 26),
    u'Date_of_the_Observation': datetime.datetime(2015, 7, 18, 16, 26),
    u'Department': u'9',
    u'Encounter_Consultant_Code': u'C2754019',
    u'Encounter_Consultant_Name': u'DR. M. BERELOWITZ',
    u'Encounter_Consultant_Type': u'',
    u'Encounter_Location_Code': u'6N',
    u'Encounter_Location_Name': u'RAL 6 NORTH',
    u'Encounter_Location_Type': u'IP',
    u'Event_Date': datetime.datetime(2015, 7, 18, 16, 47),
    u'Firstname': u'TEST',
    u'MSH_Control_ID': u'18498139',
    u'OBR-5_Priority': u'N',
    u'OBR_Sequence_ID': u'2',
    u'OBR_Status': u'F',
    u'OBR_exam_code_ID': u'ANNR',
    u'OBR_exam_code_Text': u'ANTI NEURONAL AB REFERRAL',
    u'OBX_Sequence_ID': u'14',
    u'OBX_Status': u'F',
    u'OBX_exam_code_ID': u'AN15',
    u'OBX_exam_code_Text': u'Anti-Tr antibody DNER Antigen',
    u'OBX_id': 20334314,
    u'ORC-9_Datetime_of_Transaction': datetime.datetime(2015, 7, 18, 16, 47),
    u'Observation_date': datetime.datetime(2015, 7, 18, 16, 18),
    u'Order_Number': u'',
    u'Patient_Class': u'NHS',
    u'Patient_ID_External': u'7060976728',
    u'Patient_Number': u'20552710',
    u'Relevant_Clinical_Info': u'testing',
    u'Reported_date': datetime.datetime(2015, 7, 18, 16, 26),
    u'Request_Date': datetime.datetime(2015, 7, 18, 16, 15),
    u'Requesting_Clinician': u'C4369059_Chee Ronnie',
    u'Result_ID': u'0013I245895',
    u'Result_Range': u' -',
    u'Result_Units': u'',
    u'Result_Value': u'Negative',
    u'SEX': u'F',
    u'Specimen_Site': u'^&                              ^',
    u'Surname': u'ZZZTEST',
    u'Visit_Number': u'',
    u'crs_patient_masterfile_id': None,
    u'date_inserted': datetime.datetime(2015, 7, 18, 17, 0, 2, 240000),
    u'id': 5949264,
    u'last_updated': datetime.datetime(2015, 7, 18, 17, 0, 2, 240000),
    u'visible': u'Y'},
    {u'Abnormal_Flag': u'',
    u'Accession_number': u'73151060487',
    u'DOB': datetime.datetime(1964, 1, 1, 0, 0),
    u'Date_Last_Obs_Normal': datetime.datetime(2015, 7, 18, 16, 26),
    u'Date_of_the_Observation': datetime.datetime(2015, 7, 18, 16, 26),
    u'Department': u'9',
    u'Encounter_Consultant_Code': u'C2754019',
    u'Encounter_Consultant_Name': u'DR. M. BERELOWITZ',
    u'Encounter_Consultant_Type': u'',
    u'Encounter_Location_Code': u'6N',
    u'Encounter_Location_Name': u'RAL 6 NORTH',
    u'Encounter_Location_Type': u'IP',
    u'Event_Date': datetime.datetime(2015, 7, 18, 16, 47),
    u'Firstname': u'TEST',
    u'MSH_Control_ID': u'18498139',
    u'OBR-5_Priority': u'N',
    u'OBR_Sequence_ID': u'2',
    u'OBR_Status': u'F',
    u'OBR_exam_code_ID': u'ANNR',
    u'OBR_exam_code_Text': u'ANTI NEURONAL AB REFERRAL',
    u'OBX_Sequence_ID': u'15',
    u'OBX_Status': u'F',
    u'OBX_exam_code_ID': u'RC06',
    u'OBX_exam_code_Text': u'Comment from referral lab',
    u'OBX_id': 20334315,
    u'ORC-9_Datetime_of_Transaction': datetime.datetime(2015, 7, 18, 16, 47),
    u'Observation_date': datetime.datetime(2015, 7, 18, 16, 18),
    u'Order_Number': u'',
    u'Patient_Class': u'NHS',
    u'Patient_ID_External': u'7060976728',
    u'Patient_Number': u'20552710',
    u'Relevant_Clinical_Info': u'testing',
    u'Reported_date': datetime.datetime(2015, 7, 18, 16, 26),
    u'Request_Date': datetime.datetime(2015, 7, 18, 16, 15),
    u'Requesting_Clinician': u'C4369059_Chee Ronnie',
    u'Result_ID': u'0013I245895',
    u'Result_Range': u' -',
    u'Result_Units': u'',
    u'Result_Value': u'Testing please ignore these results',
    u'SEX': u'F',
    u'Specimen_Site': u'^&                              ^',
    u'Surname': u'ZZZTEST',
    u'Visit_Number': u'',
    u'crs_patient_masterfile_id': None,
    u'date_inserted': datetime.datetime(2015, 7, 18, 17, 0, 2, 240000),
    u'id': 5949264,
    u'last_updated': datetime.datetime(2015, 7, 18, 17, 0, 2, 240000),
    u'visible': u'Y'},
    {u'Abnormal_Flag': u'',
    u'Accession_number': u'73151060487',
    u'DOB': datetime.datetime(1964, 1, 1, 0, 0),
    u'Date_Last_Obs_Normal': datetime.datetime(2015, 7, 18, 16, 25),
    u'Date_of_the_Observation': datetime.datetime(2015, 7, 18, 16, 26),
    u'Department': u'9',
    u'Encounter_Consultant_Code': u'C2754019',
    u'Encounter_Consultant_Name': u'DR. M. BERELOWITZ',
    u'Encounter_Consultant_Type': u'',
    u'Encounter_Location_Code': u'6N',
    u'Encounter_Location_Name': u'RAL 6 NORTH',
    u'Encounter_Location_Type': u'IP',
    u'Event_Date': datetime.datetime(2015, 7, 18, 16, 47),
    u'Firstname': u'TEST',
    u'MSH_Control_ID': u'18498139',
    u'OBR-5_Priority': u'N',
    u'OBR_Sequence_ID': u'2',
    u'OBR_Status': u'F',
    u'OBR_exam_code_ID': u'ANNR',
    u'OBR_exam_code_Text': u'ANTI NEURONAL AB REFERRAL',
    u'OBX_Sequence_ID': u'2',
    u'OBX_Status': u'F',
    u'OBX_exam_code_ID': u'AN2',
    u'OBX_exam_code_Text': u'Anti-Tr antibodies (Screen)',
    u'OBX_id': 20334302,
    u'ORC-9_Datetime_of_Transaction': datetime.datetime(2015, 7, 18, 16, 47),
    u'Observation_date': datetime.datetime(2015, 7, 18, 16, 18),
    u'Order_Number': u'',
    u'Patient_Class': u'NHS',
    u'Patient_ID_External': u'7060976728',
    u'Patient_Number': u'20552710',
    u'Relevant_Clinical_Info': u'testing',
    u'Reported_date': datetime.datetime(2015, 7, 18, 16, 26),
    u'Request_Date': datetime.datetime(2015, 7, 18, 16, 15),
    u'Requesting_Clinician': u'C4369059_Chee Ronnie',
    u'Result_ID': u'0013I245895',
    u'Result_Range': u' -',
    u'Result_Units': u'',
    u'Result_Value': u'Negative',
    u'SEX': u'F',
    u'Specimen_Site': u'^&                              ^',
    u'Surname': u'ZZZTEST',
    u'Visit_Number': u'',
    u'crs_patient_masterfile_id': None,
    u'date_inserted': datetime.datetime(2015, 7, 18, 17, 0, 2, 240000),
    u'id': 5949264,
    u'last_updated': datetime.datetime(2015, 7, 18, 17, 0, 2, 240000),
    u'visible': u'Y'},
    {u'Abnormal_Flag': u'',
    u'Accession_number': u'73151060487',
    u'DOB': datetime.datetime(1964, 1, 1, 0, 0),
    u'Date_Last_Obs_Normal': datetime.datetime(2015, 7, 18, 16, 25),
    u'Date_of_the_Observation': datetime.datetime(2015, 7, 18, 16, 26),
    u'Department': u'9',
    u'Encounter_Consultant_Code': u'C2754019',
    u'Encounter_Consultant_Name': u'DR. M. BERELOWITZ',
    u'Encounter_Consultant_Type': u'',
    u'Encounter_Location_Code': u'6N',
    u'Encounter_Location_Name': u'RAL 6 NORTH',
    u'Encounter_Location_Type': u'IP',
    u'Event_Date': datetime.datetime(2015, 7, 18, 16, 47),
    u'Firstname': u'TEST',
    u'MSH_Control_ID': u'18498139',
    u'OBR-5_Priority': u'N',
    u'OBR_Sequence_ID': u'2',
    u'OBR_Status': u'F',
    u'OBR_exam_code_ID': u'ANNR',
    u'OBR_exam_code_Text': u'ANTI NEURONAL AB REFERRAL',
    u'OBX_Sequence_ID': u'3',
    u'OBX_Status': u'F',
    u'OBX_exam_code_ID': u'AN3',
    u'OBX_exam_code_Text': u'Other Cerebellar Cells',
    u'OBX_id': 20334303,
    u'ORC-9_Datetime_of_Transaction': datetime.datetime(2015, 7, 18, 16, 47),
    u'Observation_date': datetime.datetime(2015, 7, 18, 16, 18),
    u'Order_Number': u'',
    u'Patient_Class': u'NHS',
    u'Patient_ID_External': u'7060976728',
    u'Patient_Number': u'20552710',
    u'Relevant_Clinical_Info': u'testing',
    u'Reported_date': datetime.datetime(2015, 7, 18, 16, 26),
    u'Request_Date': datetime.datetime(2015, 7, 18, 16, 15),
    u'Requesting_Clinician': u'C4369059_Chee Ronnie',
    u'Result_ID': u'0013I245895',
    u'Result_Range': u' -',
    u'Result_Units': u'',
    u'Result_Value': u'Negative',
    u'SEX': u'F',
    u'Specimen_Site': u'^&                              ^',
    u'Surname': u'ZZZTEST',
    u'Visit_Number': u'',
    u'crs_patient_masterfile_id': None,
    u'date_inserted': datetime.datetime(2015, 7, 18, 17, 0, 2, 240000),
    u'id': 5949264,
    u'last_updated': datetime.datetime(2015, 7, 18, 17, 0, 2, 240000),
    u'visible': u'Y'},
    {u'Abnormal_Flag': u'',
    u'Accession_number': u'73151060487',
    u'DOB': datetime.datetime(1964, 1, 1, 0, 0),
    u'Date_Last_Obs_Normal': datetime.datetime(2015, 7, 18, 16, 25),
    u'Date_of_the_Observation': datetime.datetime(2015, 7, 18, 16, 26),
    u'Department': u'9',
    u'Encounter_Consultant_Code': u'C2754019',
    u'Encounter_Consultant_Name': u'DR. M. BERELOWITZ',
    u'Encounter_Consultant_Type': u'',
    u'Encounter_Location_Code': u'6N',
    u'Encounter_Location_Name': u'RAL 6 NORTH',
    u'Encounter_Location_Type': u'IP',
    u'Event_Date': datetime.datetime(2015, 7, 18, 16, 47),
    u'Firstname': u'TEST',
    u'MSH_Control_ID': u'18498139',
    u'OBR-5_Priority': u'N',
    u'OBR_Sequence_ID': u'2',
    u'OBR_Status': u'F',
    u'OBR_exam_code_ID': u'ANNR',
    u'OBR_exam_code_Text': u'ANTI NEURONAL AB REFERRAL',
    u'OBX_Sequence_ID': u'4',
    u'OBX_Status': u'F',
    u'OBX_exam_code_ID': u'AN4',
    u'OBX_exam_code_Text': u'IgG White Matter (myelin)',
    u'OBX_id': 20334304,
    u'ORC-9_Datetime_of_Transaction': datetime.datetime(2015, 7, 18, 16, 47),
    u'Observation_date': datetime.datetime(2015, 7, 18, 16, 18),
    u'Order_Number': u'',
    u'Patient_Class': u'NHS',
    u'Patient_ID_External': u'7060976728',
    u'Patient_Number': u'20552710',
    u'Relevant_Clinical_Info': u'testing',
    u'Reported_date': datetime.datetime(2015, 7, 18, 16, 26),
    u'Request_Date': datetime.datetime(2015, 7, 18, 16, 15),
    u'Requesting_Clinician': u'C4369059_Chee Ronnie',
    u'Result_ID': u'0013I245895',
    u'Result_Range': u' -',
    u'Result_Units': u'',
    u'Result_Value': u'Negative',
    u'SEX': u'F',
    u'Specimen_Site': u'^&                              ^',
    u'Surname': u'ZZZTEST',
    u'Visit_Number': u'',
    u'crs_patient_masterfile_id': None,
    u'date_inserted': datetime.datetime(2015, 7, 18, 17, 0, 2, 240000),
    u'id': 5949264,
    u'last_updated': datetime.datetime(2015, 7, 18, 17, 0, 2, 240000),
    u'visible': u'Y'},
    {u'Abnormal_Flag': u'',
    u'Accession_number': u'73151862499',
    u'DOB': datetime.datetime(1983, 8, 2, 0, 0),
    u'Date_Last_Obs_Normal': datetime.datetime(2015, 12, 22, 10, 7),
    u'Date_of_the_Observation': datetime.datetime(2015, 12, 22, 10, 7),
    u'Department': u'1',
    u'Encounter_Consultant_Code': u'C3435362',
    u'Encounter_Consultant_Name': u'DR. A. MARTIN',
    u'Encounter_Consultant_Type': u'',
    u'Encounter_Location_Code': u'NS',
    u'Encounter_Location_Name': u'Not specified/unknown location',
    u'Encounter_Location_Type': u'UNK',
    u'Event_Date': datetime.datetime(2015, 12, 22, 10, 9),
    u'Firstname': u'FERNANDES',
    u'MSH_Control_ID': u'21127572',
    u'OBR-5_Priority': u'N',
    u'OBR_Sequence_ID': u'1',
    u'OBR_Status': u'F',
    u'OBR_exam_code_ID': u'HLCM',
    u'OBR_exam_code_Text': u'IGM HEVYLITE CHAINS',
    u'OBX_Sequence_ID': u'1',
    u'OBX_Status': u'F',
    u'OBX_exam_code_ID': u'HLMK',
    u'OBX_exam_code_Text': u'Hevylite IgM Kappa',
    u'OBX_id': 30851557,
    u'ORC-9_Datetime_of_Transaction': datetime.datetime(2015, 12, 22, 10, 9),
    u'Observation_date': datetime.datetime(2015, 12, 22, 10, 6),
    u'Order_Number': u'',
    u'Patient_Class': u'NHS',
    u'Patient_ID_External': u'',
    u'Patient_Number': u'20187265',
    u'Relevant_Clinical_Info': u'testing',
    u'Reported_date': datetime.datetime(2015, 12, 22, 10, 7),
    u'Request_Date': datetime.datetime(2015, 12, 22, 10, 7),
    u'Requesting_Clinician': u'C3262182_Baker Daryl',
    u'Result_ID': u'73151862499',
    u'Result_Range': u'0.29 - 1.82',
    u'Result_Units': u'g/L',
    u'Result_Value': u'1.50',
    u'SEX': u'M',
    u'Specimen_Site': u'^&                              ^',
    u'Surname': u'ZZZTEST',
    u'Visit_Number': u'',
    u'crs_patient_masterfile_id': None,
    u'date_inserted': datetime.datetime(2015, 12, 22, 10, 20, 4, 567000),
    u'id': 9053834,
    u'last_updated': datetime.datetime(2015, 12, 22, 10, 20, 4, 567000),
    u'visible': u'Y'},
    {u'Abnormal_Flag': u'',
    u'Accession_number': u'73151060487',
    u'DOB': datetime.datetime(1964, 1, 1, 0, 0),
    u'Date_Last_Obs_Normal': datetime.datetime(2015, 7, 18, 16, 25),
    u'Date_of_the_Observation': datetime.datetime(2015, 7, 18, 16, 26),
    u'Department': u'9',
    u'Encounter_Consultant_Code': u'C2754019',
    u'Encounter_Consultant_Name': u'DR. M. BERELOWITZ',
    u'Encounter_Consultant_Type': u'',
    u'Encounter_Location_Code': u'6N',
    u'Encounter_Location_Name': u'RAL 6 NORTH',
    u'Encounter_Location_Type': u'IP',
    u'Event_Date': datetime.datetime(2015, 7, 18, 16, 47),
    u'Firstname': u'TEST',
    u'MSH_Control_ID': u'18498139',
    u'OBR-5_Priority': u'N',
    u'OBR_Sequence_ID': u'1',
    u'OBR_Status': u'F',
    u'OBR_exam_code_ID': u'ANNA',
    u'OBR_exam_code_Text': u'ANTI NEURONAL ANTIBODIES',
    u'OBX_Sequence_ID': u'1',
    u'OBX_Status': u'F',
    u'OBX_exam_code_ID': u'YO',
    u'OBX_exam_code_Text': u'Purkinje Cell Ab (Yo)',
    u'OBX_id': 20334297,
    u'ORC-9_Datetime_of_Transaction': datetime.datetime(2015, 7, 18, 16, 47),
    u'Observation_date': datetime.datetime(2015, 7, 18, 16, 18),
    u'Order_Number': u'',
    u'Patient_Class': u'NHS',
    u'Patient_ID_External': u'7060976728',
    u'Patient_Number': u'20552710',
    u'Relevant_Clinical_Info': u'testing',
    u'Reported_date': datetime.datetime(2015, 7, 18, 16, 47),
    u'Request_Date': datetime.datetime(2015, 7, 18, 16, 15),
    u'Requesting_Clinician': u'C4369059_Chee Ronnie',
    u'Result_ID': u'0013I245895',
    u'Result_Range': u' -',
    u'Result_Units': u'',
    u'Result_Value': u'Negative',
    u'SEX': u'F',
    u'Specimen_Site': u'^&                              ^',
    u'Surname': u'ZZZTEST',
    u'Visit_Number': u'',
    u'crs_patient_masterfile_id': None,
    u'date_inserted': datetime.datetime(2015, 7, 18, 17, 0, 2, 223000),
    u'id': 5949263,
    u'last_updated': datetime.datetime(2015, 7, 18, 17, 0, 2, 223000),
    u'visible': u'Y'},
    {u'Abnormal_Flag': u'',
    u'Accession_number': u'73151060487',
    u'DOB': datetime.datetime(1964, 1, 1, 0, 0),
    u'Date_Last_Obs_Normal': datetime.datetime(2015, 7, 18, 16, 25),
    u'Date_of_the_Observation': datetime.datetime(2015, 7, 18, 16, 26),
    u'Department': u'9',
    u'Encounter_Consultant_Code': u'C2754019',
    u'Encounter_Consultant_Name': u'DR. M. BERELOWITZ',
    u'Encounter_Consultant_Type': u'',
    u'Encounter_Location_Code': u'6N',
    u'Encounter_Location_Name': u'RAL 6 NORTH',
    u'Encounter_Location_Type': u'IP',
    u'Event_Date': datetime.datetime(2015, 7, 18, 16, 47),
    u'Firstname': u'TEST',
    u'MSH_Control_ID': u'18498139',
    u'OBR-5_Priority': u'N',
    u'OBR_Sequence_ID': u'1',
    u'OBR_Status': u'F',
    u'OBR_exam_code_ID': u'ANNA',
    u'OBR_exam_code_Text': u'ANTI NEURONAL ANTIBODIES',
    u'OBX_Sequence_ID': u'2',
    u'OBX_Status': u'F',
    u'OBX_exam_code_ID': u'HU',
    u'OBX_exam_code_Text': u'Neuronal Nuclear Ab1 (Hu)',
    u'OBX_id': 20334298,
    u'ORC-9_Datetime_of_Transaction': datetime.datetime(2015, 7, 18, 16, 47),
    u'Observation_date': datetime.datetime(2015, 7, 18, 16, 18),
    u'Order_Number': u'',
    u'Patient_Class': u'NHS',
    u'Patient_ID_External': u'7060976728',
    u'Patient_Number': u'20552710',
    u'Relevant_Clinical_Info': u'testing',
    u'Reported_date': datetime.datetime(2015, 7, 18, 16, 47),
    u'Request_Date': datetime.datetime(2015, 7, 18, 16, 15),
    u'Requesting_Clinician': u'C4369059_Chee Ronnie',
    u'Result_ID': u'0013I245895',
    u'Result_Range': u' -',
    u'Result_Units': u'',
    u'Result_Value': u'Negative',
    u'SEX': u'F',
    u'Specimen_Site': u'^&                              ^',
    u'Surname': u'ZZZTEST',
    u'Visit_Number': u'',
    u'crs_patient_masterfile_id': None,
    u'date_inserted': datetime.datetime(2015, 7, 18, 17, 0, 2, 223000),
    u'id': 5949263,
    u'last_updated': datetime.datetime(2015, 7, 18, 17, 0, 2, 223000),
    u'visible': u'Y'},
    {u'Abnormal_Flag': u'',
    u'Accession_number': u'73151060487',
    u'DOB': datetime.datetime(1964, 1, 1, 0, 0),
    u'Date_Last_Obs_Normal': datetime.datetime(2015, 7, 18, 16, 47),
    u'Date_of_the_Observation': datetime.datetime(2015, 7, 18, 16, 47),
    u'Department': u'9',
    u'Encounter_Consultant_Code': u'C2754019',
    u'Encounter_Consultant_Name': u'DR. M. BERELOWITZ',
    u'Encounter_Consultant_Type': u'',
    u'Encounter_Location_Code': u'6N',
    u'Encounter_Location_Name': u'RAL 6 NORTH',
    u'Encounter_Location_Type': u'IP',
    u'Event_Date': datetime.datetime(2015, 7, 18, 16, 47),
    u'Firstname': u'TEST',
    u'MSH_Control_ID': u'18498139',
    u'OBR-5_Priority': u'N',
    u'OBR_Sequence_ID': u'1',
    u'OBR_Status': u'F',
    u'OBR_exam_code_ID': u'ANNA',
    u'OBR_exam_code_Text': u'ANTI NEURONAL ANTIBODIES',
    u'OBX_Sequence_ID': u'3',
    u'OBX_Status': u'F',
    u'OBX_exam_code_ID': u'RI',
    u'OBX_exam_code_Text': u'Neuronal Nuclear Ab2 (Ri)',
    u'OBX_id': 20334299,
    u'ORC-9_Datetime_of_Transaction': datetime.datetime(2015, 7, 18, 16, 47),
    u'Observation_date': datetime.datetime(2015, 7, 18, 16, 18),
    u'Order_Number': u'',
    u'Patient_Class': u'NHS',
    u'Patient_ID_External': u'7060976728',
    u'Patient_Number': u'20552710',
    u'Relevant_Clinical_Info': u'testing',
    u'Reported_date': datetime.datetime(2015, 7, 18, 16, 47),
    u'Request_Date': datetime.datetime(2015, 7, 18, 16, 15),
    u'Requesting_Clinician': u'C4369059_Chee Ronnie',
    u'Result_ID': u'0013I245895',
    u'Result_Range': u' -',
    u'Result_Units': u'',
    u'Result_Value': u'POSITIVE',
    u'SEX': u'F',
    u'Specimen_Site': u'^&                              ^',
    u'Surname': u'ZZZTEST',
    u'Visit_Number': u'',
    u'crs_patient_masterfile_id': None,
    u'date_inserted': datetime.datetime(2015, 7, 18, 17, 0, 2, 223000),
    u'id': 5949263,
    u'last_updated': datetime.datetime(2015, 7, 18, 17, 0, 2, 223000),
    u'visible': u'Y'},
    {u'Abnormal_Flag': u'',
    u'Accession_number': u'73151060487',
    u'DOB': datetime.datetime(1964, 1, 1, 0, 0),
    u'Date_Last_Obs_Normal': datetime.datetime(2015, 7, 18, 16, 25),
    u'Date_of_the_Observation': datetime.datetime(2015, 7, 18, 16, 26),
    u'Department': u'9',
    u'Encounter_Consultant_Code': u'C2754019',
    u'Encounter_Consultant_Name': u'DR. M. BERELOWITZ',
    u'Encounter_Consultant_Type': u'',
    u'Encounter_Location_Code': u'6N',
    u'Encounter_Location_Name': u'RAL 6 NORTH',
    u'Encounter_Location_Type': u'IP',
    u'Event_Date': datetime.datetime(2015, 7, 18, 16, 47),
    u'Firstname': u'TEST',
    u'MSH_Control_ID': u'18498139',
    u'OBR-5_Priority': u'N',
    u'OBR_Sequence_ID': u'1',
    u'OBR_Status': u'F',
    u'OBR_exam_code_ID': u'ANNA',
    u'OBR_exam_code_Text': u'ANTI NEURONAL ANTIBODIES',
    u'OBX_Sequence_ID': u'4',
    u'OBX_Status': u'F',
    u'OBX_exam_code_ID': u'ANNC',
    u'OBX_exam_code_Text': u'Neuronal Comment',
    u'OBX_id': 20334300,
    u'ORC-9_Datetime_of_Transaction': datetime.datetime(2015, 7, 18, 16, 47),
    u'Observation_date': datetime.datetime(2015, 7, 18, 16, 18),
    u'Order_Number': u'',
    u'Patient_Class': u'NHS',
    u'Patient_ID_External': u'7060976728',
    u'Patient_Number': u'20552710',
    u'Relevant_Clinical_Info': u'testing',
    u'Reported_date': datetime.datetime(2015, 7, 18, 16, 47),
    u'Request_Date': datetime.datetime(2015, 7, 18, 16, 15),
    u'Requesting_Clinician': u'C4369059_Chee Ronnie',
    u'Result_ID': u'0013I245895',
    u'Result_Range': u' -',
    u'Result_Units': u'',
    u'Result_Value': u'Testing please ignore these results',
    u'SEX': u'F',
    u'Specimen_Site': u'^&                              ^',
    u'Surname': u'ZZZTEST',
    u'Visit_Number': u'',
    u'crs_patient_masterfile_id': None,
    u'date_inserted': datetime.datetime(2015, 7, 18, 17, 0, 2, 223000),
    u'id': 5949263,
    u'last_updated': datetime.datetime(2015, 7, 18, 17, 0, 2, 223000),
    u'visible': u'Y'},
    {u'Abnormal_Flag': u'',
    u'Accession_number': u'73151862499',
    u'DOB': datetime.datetime(1983, 8, 2, 0, 0),
    u'Date_Last_Obs_Normal': datetime.datetime(2015, 12, 22, 10, 7),
    u'Date_of_the_Observation': datetime.datetime(2015, 12, 22, 10, 7),
    u'Department': u'1',
    u'Encounter_Consultant_Code': u'C3435362',
    u'Encounter_Consultant_Name': u'DR. A. MARTIN',
    u'Encounter_Consultant_Type': u'',
    u'Encounter_Location_Code': u'NS',
    u'Encounter_Location_Name': u'Not specified/unknown location',
    u'Encounter_Location_Type': u'UNK',
    u'Event_Date': datetime.datetime(2015, 12, 22, 10, 9),
    u'Firstname': u'FERNANDES',
    u'MSH_Control_ID': u'21127572',
    u'OBR-5_Priority': u'N',
    u'OBR_Sequence_ID': u'1',
    u'OBR_Status': u'F',
    u'OBR_exam_code_ID': u'HLCM',
    u'OBR_exam_code_Text': u'IGM HEVYLITE CHAINS',
    u'OBX_Sequence_ID': u'2',
    u'OBX_Status': u'F',
    u'OBX_exam_code_ID': u'HLML',
    u'OBX_exam_code_Text': u'Hevylite IgM Lambda',
    u'OBX_id': 30851558,
    u'ORC-9_Datetime_of_Transaction': datetime.datetime(2015, 12, 22, 10, 9),
    u'Observation_date': datetime.datetime(2015, 12, 22, 10, 6),
    u'Order_Number': u'',
    u'Patient_Class': u'NHS',
    u'Patient_ID_External': u'',
    u'Patient_Number': u'20187265',
    u'Relevant_Clinical_Info': u'testing',
    u'Reported_date': datetime.datetime(2015, 12, 22, 10, 7),
    u'Request_Date': datetime.datetime(2015, 12, 22, 10, 7),
    u'Requesting_Clinician': u'C3262182_Baker Daryl',
    u'Result_ID': u'73151862499',
    u'Result_Range': u'0.17 - 0.94',
    u'Result_Units': u'g/L',
    u'Result_Value': u'0.50',
    u'SEX': u'M',
    u'Specimen_Site': u'^&                              ^',
    u'Surname': u'ZZZTEST',
    u'Visit_Number': u'',
    u'crs_patient_masterfile_id': None,
    u'date_inserted': datetime.datetime(2015, 12, 22, 10, 20, 4, 567000),
    u'id': 9053834,
    u'last_updated': datetime.datetime(2015, 12, 22, 10, 20, 4, 567000),
    u'visible': u'Y'},
    {u'Abnormal_Flag': u'H',
    u'Accession_number': u'73151862499',
    u'DOB': datetime.datetime(1983, 8, 2, 0, 0),
    u'Date_Last_Obs_Normal': datetime.datetime(2015, 12, 22, 10, 7),
    u'Date_of_the_Observation': datetime.datetime(2015, 12, 22, 10, 7),
    u'Department': u'1',
    u'Encounter_Consultant_Code': u'C3435362',
    u'Encounter_Consultant_Name': u'DR. A. MARTIN',
    u'Encounter_Consultant_Type': u'',
    u'Encounter_Location_Code': u'NS',
    u'Encounter_Location_Name': u'Not specified/unknown location',
    u'Encounter_Location_Type': u'UNK',
    u'Event_Date': datetime.datetime(2015, 12, 22, 10, 9),
    u'Firstname': u'FERNANDES',
    u'MSH_Control_ID': u'21127572',
    u'OBR-5_Priority': u'N',
    u'OBR_Sequence_ID': u'1',
    u'OBR_Status': u'F',
    u'OBR_exam_code_ID': u'HLCM',
    u'OBR_exam_code_Text': u'IGM HEVYLITE CHAINS',
    u'OBX_Sequence_ID': u'3',
    u'OBX_Status': u'F',
    u'OBX_exam_code_ID': u'HLMR',
    u'OBX_exam_code_Text': u'Hevylite IgM K:L Ratio',
    u'OBX_id': 30851559,
    u'ORC-9_Datetime_of_Transaction': datetime.datetime(2015, 12, 22, 10, 9),
    u'Observation_date': datetime.datetime(2015, 12, 22, 10, 6),
    u'Order_Number': u'',
    u'Patient_Class': u'NHS',
    u'Patient_ID_External': u'',
    u'Patient_Number': u'20187265',
    u'Relevant_Clinical_Info': u'testing',
    u'Reported_date': datetime.datetime(2015, 12, 22, 10, 7),
    u'Request_Date': datetime.datetime(2015, 12, 22, 10, 7),
    u'Requesting_Clinician': u'C3262182_Baker Daryl',
    u'Result_ID': u'73151862499',
    u'Result_Range': u'0.96 - 2.3',
    u'Result_Units': u'',
    u'Result_Value': u'3.00',
    u'SEX': u'M',
    u'Specimen_Site': u'^&                              ^',
    u'Surname': u'ZZZTEST',
    u'Visit_Number': u'',
    u'crs_patient_masterfile_id': None,
    u'date_inserted': datetime.datetime(2015, 12, 22, 10, 20, 4, 567000),
    u'id': 9053834,
    u'last_updated': datetime.datetime(2015, 12, 22, 10, 20, 4, 567000),
    u'visible': u'Y'},
    {u'Abnormal_Flag': u'',
    u'Accession_number': u'73151862499',
    u'DOB': datetime.datetime(1983, 8, 2, 0, 0),
    u'Date_Last_Obs_Normal': datetime.datetime(2015, 12, 22, 10, 7),
    u'Date_of_the_Observation': datetime.datetime(2015, 12, 22, 10, 7),
    u'Department': u'1',
    u'Encounter_Consultant_Code': u'C3435362',
    u'Encounter_Consultant_Name': u'DR. A. MARTIN',
    u'Encounter_Consultant_Type': u'',
    u'Encounter_Location_Code': u'NS',
    u'Encounter_Location_Name': u'Not specified/unknown location',
    u'Encounter_Location_Type': u'UNK',
    u'Event_Date': datetime.datetime(2015, 12, 22, 10, 9),
    u'Firstname': u'FERNANDES',
    u'MSH_Control_ID': u'21127572',
    u'OBR-5_Priority': u'N',
    u'OBR_Sequence_ID': u'1',
    u'OBR_Status': u'F',
    u'OBR_exam_code_ID': u'HLCM',
    u'OBR_exam_code_Text': u'IGM HEVYLITE CHAINS',
    u'OBX_Sequence_ID': u'4',
    u'OBX_Status': u'F',
    u'OBX_exam_code_ID': u'IGM',
    u'OBX_exam_code_Text': u'Immunoglobulin M',
    u'OBX_id': 30851560,
    u'ORC-9_Datetime_of_Transaction': datetime.datetime(2015, 12, 22, 10, 9),
    u'Observation_date': datetime.datetime(2015, 12, 22, 10, 6),
    u'Order_Number': u'',
    u'Patient_Class': u'NHS',
    u'Patient_ID_External': u'',
    u'Patient_Number': u'20187265',
    u'Relevant_Clinical_Info': u'testing',
    u'Reported_date': datetime.datetime(2015, 12, 22, 10, 7),
    u'Request_Date': datetime.datetime(2015, 12, 22, 10, 7),
    u'Requesting_Clinician': u'C3262182_Baker Daryl',
    u'Result_ID': u'73151862499',
    u'Result_Range': u'0.4 - 2.3',
    u'Result_Units': u'g/L',
    u'Result_Value': u'2.0',
    u'SEX': u'M',
    u'Specimen_Site': u'^&                              ^',
    u'Surname': u'ZZZTEST',
    u'Visit_Number': u'',
    u'crs_patient_masterfile_id': None,
    u'date_inserted': datetime.datetime(2015, 12, 22, 10, 20, 4, 567000),
    u'id': 9053834,
    u'last_updated': datetime.datetime(2015, 12, 22, 10, 20, 4, 567000),
    u'visible': u'Y'},
    {u'Abnormal_Flag': u'',
    u'Accession_number': u'',
    u'DOB': datetime.datetime(1975, 5, 1, 0, 0),
    u'Date_Last_Obs_Normal': datetime.datetime(2016, 11, 22, 13, 3),
    u'Date_of_the_Observation': datetime.datetime(2016, 11, 22, 13, 3),
    u'Department': u'3',
    u'Encounter_Consultant_Code': u'C3518759',
    u'Encounter_Consultant_Name': u'MR. M.A. AL-AKRAA',
    u'Encounter_Consultant_Type': u'49',
    u'Encounter_Location_Code': u'3EC',
    u'Encounter_Location_Name': u'RAL 3 EAST C',
    u'Encounter_Location_Type': u'OP',
    u'Event_Date': datetime.datetime(2016, 11, 22, 13, 3),
    u'Firstname': u'TESTING',
    u'MSH_Control_ID': u'26732810',
    u'OBR-5_Priority': u'N',
    u'OBR_Sequence_ID': u'1',
    u'OBR_Status': u'F',
    u'OBR_exam_code_ID': u'WS',
    u'OBR_exam_code_Text': u'WOUND SWAB CULTURE + SENS',
    u'OBX_Sequence_ID': u'1',
    u'OBX_Status': u'F',
    u'OBX_exam_code_ID': u'CRES',
    u'OBX_exam_code_Text': u'Culture Result',
    u'OBX_id': 53916547,
    u'ORC-9_Datetime_of_Transaction': datetime.datetime(2016, 11, 22, 13, 3),
    u'Observation_date': datetime.datetime(2016, 11, 22, 13, 2),
    u'Order_Number': u'',
    u'Patient_Class': u'NHS',
    u'Patient_ID_External': u'7065093557',
    u'Patient_Number': u'20071683',
    u'Relevant_Clinical_Info': u'Testing Chlamydia PCR',
    u'Reported_date': datetime.datetime(2016, 11, 22, 13, 3),
    u'Request_Date': datetime.datetime(2016, 11, 22, 13, 2),
    u'Requesting_Clinician': u'',
    u'Result_ID': u'0015M383790',
    u'Result_Range': u' -',
    u'Result_Units': u'',
    u'Result_Value': u'No significant growth',
    u'SEX': u'F',
    u'Specimen_Site': u'S     ^Swab & Tips etc.         &N    ^Not stated',
    u'Surname': u'ZZZTEST',
    u'Visit_Number': u'',
    u'crs_patient_masterfile_id': None,
    u'date_inserted': datetime.datetime(2016, 11, 22, 13, 10, 7, 797000),
    u'id': 15889124,
    u'last_updated': datetime.datetime(2016, 11, 22, 13, 10, 7, 797000),
    u'visible': u'Y'},
    {u'Abnormal_Flag': u'',
    u'Accession_number': u'',
    u'DOB': datetime.datetime(1975, 5, 1, 0, 0),
    u'Date_Last_Obs_Normal': datetime.datetime(2016, 11, 22, 13, 3),
    u'Date_of_the_Observation': datetime.datetime(2016, 11, 22, 13, 3),
    u'Department': u'3',
    u'Encounter_Consultant_Code': u'C3518759',
    u'Encounter_Consultant_Name': u'MR. M.A. AL-AKRAA',
    u'Encounter_Consultant_Type': u'49',
    u'Encounter_Location_Code': u'3EC',
    u'Encounter_Location_Name': u'RAL 3 EAST C',
    u'Encounter_Location_Type': u'OP',
    u'Event_Date': datetime.datetime(2016, 11, 22, 13, 3),
    u'Firstname': u'TESTING',
    u'MSH_Control_ID': u'26732810',
    u'OBR-5_Priority': u'N',
    u'OBR_Sequence_ID': u'1',
    u'OBR_Status': u'F',
    u'OBR_exam_code_ID': u'WS',
    u'OBR_exam_code_Text': u'WOUND SWAB CULTURE + SENS',
    u'OBX_Sequence_ID': u'2',
    u'OBX_Status': u'F',
    u'OBX_exam_code_ID': u'MCOM',
    u'OBX_exam_code_Text': u'Comments',
    u'OBX_id': 53916548,
    u'ORC-9_Datetime_of_Transaction': datetime.datetime(2016, 11, 22, 13, 3),
    u'Observation_date': datetime.datetime(2016, 11, 22, 13, 2),
    u'Order_Number': u'',
    u'Patient_Class': u'NHS',
    u'Patient_ID_External': u'7065093557',
    u'Patient_Number': u'20071683',
    u'Relevant_Clinical_Info': u'Testing Chlamydia PCR',
    u'Reported_date': datetime.datetime(2016, 11, 22, 13, 3),
    u'Request_Date': datetime.datetime(2016, 11, 22, 13, 2),
    u'Requesting_Clinician': u'',
    u'Result_ID': u'0015M383790',
    u'Result_Range': u' -',
    u'Result_Units': u'',
    u'Result_Value': u'Preliminary Report - Final report to follow.',
    u'SEX': u'F',
    u'Specimen_Site': u'S     ^Swab & Tips etc.         &N    ^Not stated',
    u'Surname': u'ZZZTEST',
    u'Visit_Number': u'',
    u'crs_patient_masterfile_id': None,
    u'date_inserted': datetime.datetime(2016, 11, 22, 13, 10, 7, 797000),
    u'id': 15889124,
    u'last_updated': datetime.datetime(2016, 11, 22, 13, 10, 7, 797000),
    u'visible': u'Y'},
    {u'Abnormal_Flag': u'',
    u'Accession_number': u'',
    u'DOB': datetime.datetime(1975, 5, 1, 0, 0),
    u'Date_Last_Obs_Normal': datetime.datetime(2016, 11, 22, 13, 2),
    u'Date_of_the_Observation': datetime.datetime(2016, 11, 22, 13, 3),
    u'Department': u'3',
    u'Encounter_Consultant_Code': u'C3518759',
    u'Encounter_Consultant_Name': u'MR. M.A. AL-AKRAA',
    u'Encounter_Consultant_Type': u'49',
    u'Encounter_Location_Code': u'3EC',
    u'Encounter_Location_Name': u'RAL 3 EAST C',
    u'Encounter_Location_Type': u'OP',
    u'Event_Date': datetime.datetime(2016, 11, 22, 13, 3),
    u'Firstname': u'TESTING',
    u'MSH_Control_ID': u'26732810',
    u'OBR-5_Priority': u'N',
    u'OBR_Sequence_ID': u'1',
    u'OBR_Status': u'F',
    u'OBR_exam_code_ID': u'WS',
    u'OBR_exam_code_Text': u'WOUND SWAB CULTURE + SENS',
    u'OBX_Sequence_ID': u'3',
    u'OBX_Status': u'F',
    u'OBX_exam_code_ID': u'CLDE',
    u'OBX_exam_code_Text': u'Clinical Details',
    u'OBX_id': 53916549,
    u'ORC-9_Datetime_of_Transaction': datetime.datetime(2016, 11, 22, 13, 3),
    u'Observation_date': datetime.datetime(2016, 11, 22, 13, 2),
    u'Order_Number': u'',
    u'Patient_Class': u'NHS',
    u'Patient_ID_External': u'7065093557',
    u'Patient_Number': u'20071683',
    u'Relevant_Clinical_Info': u'Testing Chlamydia PCR',
    u'Reported_date': datetime.datetime(2016, 11, 22, 13, 3),
    u'Request_Date': datetime.datetime(2016, 11, 22, 13, 2),
    u'Requesting_Clinician': u'',
    u'Result_ID': u'0015M383790',
    u'Result_Range': u' -',
    u'Result_Units': u'',
    u'Result_Value': u'Testing Chlamydia PCR',
    u'SEX': u'F',
    u'Specimen_Site': u'S     ^Swab & Tips etc.         &N    ^Not stated',
    u'Surname': u'ZZZTEST',
    u'Visit_Number': u'',
    u'crs_patient_masterfile_id': None,
    u'date_inserted': datetime.datetime(2016, 11, 22, 13, 10, 7, 797000),
    u'id': 15889124,
    u'last_updated': datetime.datetime(2016, 11, 22, 13, 10, 7, 797000),
    u'visible': u'Y'},
    {u'Abnormal_Flag': u'',
    u'Accession_number': u'',
    u'DOB': datetime.datetime(1975, 5, 1, 0, 0),
    u'Date_Last_Obs_Normal': datetime.datetime(2016, 11, 22, 13, 2),
    u'Date_of_the_Observation': datetime.datetime(2016, 11, 22, 13, 3),
    u'Department': u'3',
    u'Encounter_Consultant_Code': u'C3518759',
    u'Encounter_Consultant_Name': u'MR. M.A. AL-AKRAA',
    u'Encounter_Consultant_Type': u'49',
    u'Encounter_Location_Code': u'3EC',
    u'Encounter_Location_Name': u'RAL 3 EAST C',
    u'Encounter_Location_Type': u'OP',
    u'Event_Date': datetime.datetime(2016, 11, 22, 13, 3),
    u'Firstname': u'TESTING',
    u'MSH_Control_ID': u'26732810',
    u'OBR-5_Priority': u'N',
    u'OBR_Sequence_ID': u'1',
    u'OBR_Status': u'F',
    u'OBR_exam_code_ID': u'WS',
    u'OBR_exam_code_Text': u'WOUND SWAB CULTURE + SENS',
    u'OBX_Sequence_ID': u'4',
    u'OBX_Status': u'F',
    u'OBX_exam_code_ID': u'MCC1',
    u'OBX_exam_code_Text': u'Clinical comments',
    u'OBX_id': 53916550,
    u'ORC-9_Datetime_of_Transaction': datetime.datetime(2016, 11, 22, 13, 3),
    u'Observation_date': datetime.datetime(2016, 11, 22, 13, 2),
    u'Order_Number': u'',
    u'Patient_Class': u'NHS',
    u'Patient_ID_External': u'7065093557',
    u'Patient_Number': u'20071683',
    u'Relevant_Clinical_Info': u'Testing Chlamydia PCR',
    u'Reported_date': datetime.datetime(2016, 11, 22, 13, 3),
    u'Request_Date': datetime.datetime(2016, 11, 22, 13, 2),
    u'Requesting_Clinician': u'',
    u'Result_ID': u'0015M383790',
    u'Result_Range': u' -',
    u'Result_Units': u'',
    u'Result_Value': u'View order information, in Cerner system, to see~body site                  for this sample.',
    u'SEX': u'F',
    u'Specimen_Site': u'S     ^Swab & Tips etc.         &N    ^Not stated',
    u'Surname': u'ZZZTEST',
    u'Visit_Number': u'',
    u'crs_patient_masterfile_id': None,
    u'date_inserted': datetime.datetime(2016, 11, 22, 13, 10, 7, 797000),
    u'id': 15889124,
    u'last_updated': datetime.datetime(2016, 11, 22, 13, 10, 7, 797000),
    u'visible': u'Y'},
    {u'Abnormal_Flag': u'',
    u'Accession_number': u'73161686101',
    u'DOB': datetime.datetime(1975, 5, 1, 0, 0),
    u'Date_Last_Obs_Normal': datetime.datetime(2016, 11, 22, 13, 4),
    u'Date_of_the_Observation': datetime.datetime(2016, 11, 22, 13, 5),
    u'Department': u'3',
    u'Encounter_Consultant_Code': u'C3518759',
    u'Encounter_Consultant_Name': u'MR. M.A. AL-AKRAA',
    u'Encounter_Consultant_Type': u'49',
    u'Encounter_Location_Code': u'3EC',
    u'Encounter_Location_Name': u'RAL 3 EAST C',
    u'Encounter_Location_Type': u'OP',
    u'Event_Date': datetime.datetime(2016, 11, 22, 13, 5),
    u'Firstname': u'TESTING',
    u'MSH_Control_ID': u'26732898',
    u'OBR-5_Priority': u'N',
    u'OBR_Sequence_ID': u'1',
    u'OBR_Status': u'F',
    u'OBR_exam_code_ID': u'XCHP',
    u'OBR_exam_code_Text': u'CHLAMYDIA SEROLOGY',
    u'OBX_Sequence_ID': u'1',
    u'OBX_Status': u'F',
    u'OBX_exam_code_ID': u'CHL2',
    u'OBX_exam_code_Text': u'Chlamydia Ref. Lab. name',
    u'OBX_id': 53916745,
    u'ORC-9_Datetime_of_Transaction': datetime.datetime(2016, 11, 22, 13, 5),
    u'Observation_date': datetime.datetime(2016, 11, 22, 13, 4),
    u'Order_Number': u'',
    u'Patient_Class': u'NHS',
    u'Patient_ID_External': u'7065093557',
    u'Patient_Number': u'20071683',
    u'Relevant_Clinical_Info': u'Testing',
    u'Reported_date': datetime.datetime(2016, 11, 22, 13, 4),
    u'Request_Date': datetime.datetime(2016, 11, 22, 13, 4),
    u'Requesting_Clinician': u'C4317272_Smith Eliza',
    u'Result_ID': u'0015M383791',
    u'Result_Range': u' -',
    u'Result_Units': u'',
    u'Result_Value': u'Test',
    u'SEX': u'F',
    u'Specimen_Site': u'SERO  ^Serology / PCR Specimen  &N    ^Not stated',
    u'Surname': u'ZZZTEST',
    u'Visit_Number': u'',
    u'crs_patient_masterfile_id': None,
    u'date_inserted': datetime.datetime(2016, 11, 22, 13, 10, 10, 880000),
    u'id': 15889179,
    u'last_updated': datetime.datetime(2016, 11, 22, 13, 10, 10, 880000),
    u'visible': u'Y'},
    {u'Abnormal_Flag': u'',
    u'Accession_number': u'73161686101',
    u'DOB': datetime.datetime(1975, 5, 1, 0, 0),
    u'Date_Last_Obs_Normal': datetime.datetime(2016, 11, 22, 13, 4),
    u'Date_of_the_Observation': datetime.datetime(2016, 11, 22, 13, 5),
    u'Department': u'3',
    u'Encounter_Consultant_Code': u'C3518759',
    u'Encounter_Consultant_Name': u'MR. M.A. AL-AKRAA',
    u'Encounter_Consultant_Type': u'49',
    u'Encounter_Location_Code': u'3EC',
    u'Encounter_Location_Name': u'RAL 3 EAST C',
    u'Encounter_Location_Type': u'OP',
    u'Event_Date': datetime.datetime(2016, 11, 22, 13, 5),
    u'Firstname': u'TESTING',
    u'MSH_Control_ID': u'26732898',
    u'OBR-5_Priority': u'N',
    u'OBR_Sequence_ID': u'1',
    u'OBR_Status': u'F',
    u'OBR_exam_code_ID': u'XCHP',
    u'OBR_exam_code_Text': u'CHLAMYDIA SEROLOGY',
    u'OBX_Sequence_ID': u'2',
    u'OBX_Status': u'F',
    u'OBX_exam_code_ID': u'CHSP',
    u'OBX_exam_code_Text': u'Sample description',
    u'OBX_id': 53916746,
    u'ORC-9_Datetime_of_Transaction': datetime.datetime(2016, 11, 22, 13, 5),
    u'Observation_date': datetime.datetime(2016, 11, 22, 13, 4),
    u'Order_Number': u'',
    u'Patient_Class': u'NHS',
    u'Patient_ID_External': u'7065093557',
    u'Patient_Number': u'20071683',
    u'Relevant_Clinical_Info': u'Testing',
    u'Reported_date': datetime.datetime(2016, 11, 22, 13, 4),
    u'Request_Date': datetime.datetime(2016, 11, 22, 13, 4),
    u'Requesting_Clinician': u'C4317272_Smith Eliza',
    u'Result_ID': u'0015M383791',
    u'Result_Range': u' -',
    u'Result_Units': u'',
    u'Result_Value': u'Test',
    u'SEX': u'F',
    u'Specimen_Site': u'SERO  ^Serology / PCR Specimen  &N    ^Not stated',
    u'Surname': u'ZZZTEST',
    u'Visit_Number': u'',
    u'crs_patient_masterfile_id': None,
    u'date_inserted': datetime.datetime(2016, 11, 22, 13, 10, 10, 880000),
    u'id': 15889179,
    u'last_updated': datetime.datetime(2016, 11, 22, 13, 10, 10, 880000),
    u'visible': u'Y'},
    {u'Abnormal_Flag': u'',
    u'Accession_number': u'73161686101',
    u'DOB': datetime.datetime(1975, 5, 1, 0, 0),
    u'Date_Last_Obs_Normal': datetime.datetime(2016, 11, 22, 13, 4),
    u'Date_of_the_Observation': datetime.datetime(2016, 11, 22, 13, 5),
    u'Department': u'3',
    u'Encounter_Consultant_Code': u'C3518759',
    u'Encounter_Consultant_Name': u'MR. M.A. AL-AKRAA',
    u'Encounter_Consultant_Type': u'49',
    u'Encounter_Location_Code': u'3EC',
    u'Encounter_Location_Name': u'RAL 3 EAST C',
    u'Encounter_Location_Type': u'OP',
    u'Event_Date': datetime.datetime(2016, 11, 22, 13, 5),
    u'Firstname': u'TESTING',
    u'MSH_Control_ID': u'26732898',
    u'OBR-5_Priority': u'N',
    u'OBR_Sequence_ID': u'1',
    u'OBR_Status': u'F',
    u'OBR_exam_code_ID': u'XCHP',
    u'OBR_exam_code_Text': u'CHLAMYDIA SEROLOGY',
    u'OBX_Sequence_ID': u'3',
    u'OBX_Status': u'F',
    u'OBX_exam_code_ID': u'CHPC',
    u'OBX_exam_code_Text': u'Chlamydia PCR result',
    u'OBX_id': 53916747,
    u'ORC-9_Datetime_of_Transaction': datetime.datetime(2016, 11, 22, 13, 5),
    u'Observation_date': datetime.datetime(2016, 11, 22, 13, 4),
    u'Order_Number': u'',
    u'Patient_Class': u'NHS',
    u'Patient_ID_External': u'7065093557',
    u'Patient_Number': u'20071683',
    u'Relevant_Clinical_Info': u'Testing',
    u'Reported_date': datetime.datetime(2016, 11, 22, 13, 4),
    u'Request_Date': datetime.datetime(2016, 11, 22, 13, 4),
    u'Requesting_Clinician': u'C4317272_Smith Eliza',
    u'Result_ID': u'0015M383791',
    u'Result_Range': u' -',
    u'Result_Units': u'',
    u'Result_Value': u'Test',
    u'SEX': u'F',
    u'Specimen_Site': u'SERO  ^Serology / PCR Specimen  &N    ^Not stated',
    u'Surname': u'ZZZTEST',
    u'Visit_Number': u'',
    u'crs_patient_masterfile_id': None,
    u'date_inserted': datetime.datetime(2016, 11, 22, 13, 10, 10, 880000),
    u'id': 15889179,
    u'last_updated': datetime.datetime(2016, 11, 22, 13, 10, 10, 880000),
    u'visible': u'Y'},
    {u'Abnormal_Flag': u'',
    u'Accession_number': u'73161686101',
    u'DOB': datetime.datetime(1975, 5, 1, 0, 0),
    u'Date_Last_Obs_Normal': datetime.datetime(2016, 11, 22, 13, 4),
    u'Date_of_the_Observation': datetime.datetime(2016, 11, 22, 13, 5),
    u'Department': u'3',
    u'Encounter_Consultant_Code': u'C3518759',
    u'Encounter_Consultant_Name': u'MR. M.A. AL-AKRAA',
    u'Encounter_Consultant_Type': u'49',
    u'Encounter_Location_Code': u'3EC',
    u'Encounter_Location_Name': u'RAL 3 EAST C',
    u'Encounter_Location_Type': u'OP',
    u'Event_Date': datetime.datetime(2016, 11, 22, 13, 5),
    u'Firstname': u'TESTING',
    u'MSH_Control_ID': u'26732898',
    u'OBR-5_Priority': u'N',
    u'OBR_Sequence_ID': u'1',
    u'OBR_Status': u'F',
    u'OBR_exam_code_ID': u'XCHP',
    u'OBR_exam_code_Text': u'CHLAMYDIA SEROLOGY',
    u'OBX_Sequence_ID': u'4',
    u'OBX_Status': u'F',
    u'OBX_exam_code_ID': u'CHL5',
    u'OBX_exam_code_Text': u'Chlamydia Ref. Lab. comments',
    u'OBX_id': 53916748,
    u'ORC-9_Datetime_of_Transaction': datetime.datetime(2016, 11, 22, 13, 5),
    u'Observation_date': datetime.datetime(2016, 11, 22, 13, 4),
    u'Order_Number': u'',
    u'Patient_Class': u'NHS',
    u'Patient_ID_External': u'7065093557',
    u'Patient_Number': u'20071683',
    u'Relevant_Clinical_Info': u'Testing',
    u'Reported_date': datetime.datetime(2016, 11, 22, 13, 4),
    u'Request_Date': datetime.datetime(2016, 11, 22, 13, 4),
    u'Requesting_Clinician': u'C4317272_Smith Eliza',
    u'Result_ID': u'0015M383791',
    u'Result_Range': u' -',
    u'Result_Units': u'',
    u'Result_Value': u'TEst',
    u'SEX': u'F',
    u'Specimen_Site': u'SERO  ^Serology / PCR Specimen  &N    ^Not stated',
    u'Surname': u'ZZZTEST',
    u'Visit_Number': u'',
    u'crs_patient_masterfile_id': None,
    u'date_inserted': datetime.datetime(2016, 11, 22, 13, 10, 10, 880000),
    u'id': 15889179,
    u'last_updated': datetime.datetime(2016, 11, 22, 13, 10, 10, 880000),
    u'visible': u'Y'},
    {u'Abnormal_Flag': u'',
    u'Accession_number': u'',
    u'DOB': datetime.datetime(1964, 1, 1, 0, 0),
    u'Date_Last_Obs_Normal': datetime.datetime(2015, 7, 18, 18, 0),
    u'Date_of_the_Observation': datetime.datetime(2015, 7, 20, 9, 37),
    u'Department': u'9',
    u'Encounter_Consultant_Code': u'C2754019',
    u'Encounter_Consultant_Name': u'DR. M. BERELOWITZ',
    u'Encounter_Consultant_Type': u'',
    u'Encounter_Location_Code': u'6N',
    u'Encounter_Location_Name': u'RAL 6 NORTH',
    u'Encounter_Location_Type': u'IP',
    u'Event_Date': datetime.datetime(2015, 7, 20, 9, 37),
    u'Firstname': u'TEST',
    u'MSH_Control_ID': u'18506340',
    u'OBR-5_Priority': u'N',
    u'OBR_Sequence_ID': u'1',
    u'OBR_Status': u'F',
    u'OBR_exam_code_ID': u'ANNA',
    u'OBR_exam_code_Text': u'ANTI NEURONAL ANTIBODIES',
    u'OBX_Sequence_ID': u'1',
    u'OBX_Status': u'F',
    u'OBX_exam_code_ID': u'ANNC',
    u'OBX_exam_code_Text': u'Neuronal Comment',
    u'OBX_id': 20363144,
    u'ORC-9_Datetime_of_Transaction': datetime.datetime(2015, 7, 20, 9, 37),
    u'Observation_date': datetime.datetime(2015, 7, 18, 17, 59),
    u'Order_Number': u'',
    u'Patient_Class': u'NHS',
    u'Patient_ID_External': u'7060976728',
    u'Patient_Number': u'20552710',
    u'Relevant_Clinical_Info': u'testing please ignor',
    u'Reported_date': datetime.datetime(2015, 7, 18, 18, 0),
    u'Request_Date': datetime.datetime(2015, 7, 18, 17, 59),
    u'Requesting_Clinician': u'',
    u'Result_ID': u'0013I245897',
    u'Result_Range': u' -',
    u'Result_Units': u'',
    u'Result_Value': u'sample sent for testing',
    u'SEX': u'F',
    u'Specimen_Site': u'^&                              ^',
    u'Surname': u'ZZZTEST',
    u'Visit_Number': u'',
    u'crs_patient_masterfile_id': None,
    u'date_inserted': datetime.datetime(2015, 7, 20, 9, 50, 1, 803000),
    u'id': 5958101,
    u'last_updated': datetime.datetime(2015, 7, 20, 9, 50, 1, 803000),
    u'visible': u'Y'},
    {u'Abnormal_Flag': u'',
    u'Accession_number': u'',
    u'DOB': datetime.datetime(1964, 1, 1, 0, 0),
    u'Date_Last_Obs_Normal': datetime.datetime(2015, 7, 18, 17, 37),
    u'Date_of_the_Observation': datetime.datetime(2015, 7, 20, 9, 37),
    u'Department': u'9',
    u'Encounter_Consultant_Code': u'C2754019',
    u'Encounter_Consultant_Name': u'DR. M. BERELOWITZ',
    u'Encounter_Consultant_Type': u'',
    u'Encounter_Location_Code': u'6N',
    u'Encounter_Location_Name': u'RAL 6 NORTH',
    u'Encounter_Location_Type': u'IP',
    u'Event_Date': datetime.datetime(2015, 7, 20, 9, 37),
    u'Firstname': u'TEST',
    u'MSH_Control_ID': u'18506339',
    u'OBR-5_Priority': u'N',
    u'OBR_Sequence_ID': u'1',
    u'OBR_Status': u'F',
    u'OBR_exam_code_ID': u'ANNA',
    u'OBR_exam_code_Text': u'ANTI NEURONAL ANTIBODIES',
    u'OBX_Sequence_ID': u'4',
    u'OBX_Status': u'F',
    u'OBX_exam_code_ID': u'ANNC',
    u'OBX_exam_code_Text': u'Neuronal Comment',
    u'OBX_id': 20363143,
    u'ORC-9_Datetime_of_Transaction': datetime.datetime(2015, 7, 20, 9, 37),
    u'Observation_date': datetime.datetime(2015, 7, 18, 17, 1),
    u'Order_Number': u'',
    u'Patient_Class': u'NHS',
    u'Patient_ID_External': u'7060976728',
    u'Patient_Number': u'20552710',
    u'Relevant_Clinical_Info': u'testing please ignore',
    u'Reported_date': datetime.datetime(2015, 7, 18, 17, 49),
    u'Request_Date': datetime.datetime(2015, 7, 18, 17, 1),
    u'Requesting_Clinician': u'',
    u'Result_ID': u'0013I245896',
    u'Result_Range': u' -',
    u'Result_Units': u'',
    u'Result_Value': u'Anti-Tr antibodies (Screen)  : Negative~Other Cerebellar Ce                 lls       : Negative~IgG White Matter (myelin)    : Negative~Brain homogenate We                 stern blot: Negative~_Recombinant Immunoblotting_~Anti-Hu antibodies           :                  Negative~Anti-Yo antibodies           : Negative~Anti-Ri antibodies           :                  Negative~Anti-Ma-1 antibodie          : Negative~Anti-Ma-2 antibodies         :                  Negative~Anti-CV2 (CRMP-5) antibodies : Negative~Anti-Amphiphysin antibodies  :                  Negative~Anti-Sox 1 antibodies        : Negative~Anti-Zic-4 1 antibodies      :                  Negative~Anti-Tr antibody DNER Antigen: Negative~Comment from referral lab:~Thi                 s test was referred to the Neuroimmunology~and CSF Laboratory, The National Hosp                 ital for~Neurology and Neurosurgery, Queen Square, London.',
    u'SEX': u'F',
    u'Specimen_Site': u'^&                              ^',
    u'Surname': u'ZZZTEST',
    u'Visit_Number': u'',
    u'crs_patient_masterfile_id': None,
    u'date_inserted': datetime.datetime(2015, 7, 20, 9, 50, 1, 787000),
    u'id': 5958100,
    u'last_updated': datetime.datetime(2015, 7, 20, 9, 50, 1, 787000),
    u'visible': u'Y'},
    {u'Abnormal_Flag': u'',
    u'Accession_number': u'',
    u'DOB': datetime.datetime(1964, 1, 1, 0, 0),
    u'Date_Last_Obs_Normal': datetime.datetime(2015, 7, 18, 17, 36),
    u'Date_of_the_Observation': datetime.datetime(2015, 7, 18, 17, 39),
    u'Department': u'9',
    u'Encounter_Consultant_Code': u'C2754019',
    u'Encounter_Consultant_Name': u'DR. M. BERELOWITZ',
    u'Encounter_Consultant_Type': u'',
    u'Encounter_Location_Code': u'6N',
    u'Encounter_Location_Name': u'RAL 6 NORTH',
    u'Encounter_Location_Type': u'IP',
    u'Event_Date': datetime.datetime(2015, 7, 20, 9, 37),
    u'Firstname': u'TEST',
    u'MSH_Control_ID': u'18506339',
    u'OBR-5_Priority': u'N',
    u'OBR_Sequence_ID': u'1',
    u'OBR_Status': u'F',
    u'OBR_exam_code_ID': u'ANNA',
    u'OBR_exam_code_Text': u'ANTI NEURONAL ANTIBODIES',
    u'OBX_Sequence_ID': u'1',
    u'OBX_Status': u'F',
    u'OBX_exam_code_ID': u'YO',
    u'OBX_exam_code_Text': u'Purkinje Cell Ab (Yo)',
    u'OBX_id': 20363140,
    u'ORC-9_Datetime_of_Transaction': datetime.datetime(2015, 7, 20, 9, 37),
    u'Observation_date': datetime.datetime(2015, 7, 18, 17, 1),
    u'Order_Number': u'',
    u'Patient_Class': u'NHS',
    u'Patient_ID_External': u'7060976728',
    u'Patient_Number': u'20552710',
    u'Relevant_Clinical_Info': u'testing please ignore',
    u'Reported_date': datetime.datetime(2015, 7, 18, 17, 49),
    u'Request_Date': datetime.datetime(2015, 7, 18, 17, 1),
    u'Requesting_Clinician': u'',
    u'Result_ID': u'0013I245896',
    u'Result_Range': u' -',
    u'Result_Units': u'',
    u'Result_Value': u'Negative',
    u'SEX': u'F',
    u'Specimen_Site': u'^&                              ^',
    u'Surname': u'ZZZTEST',
    u'Visit_Number': u'',
    u'crs_patient_masterfile_id': None,
    u'date_inserted': datetime.datetime(2015, 7, 20, 9, 50, 1, 787000),
    u'id': 5958100,
    u'last_updated': datetime.datetime(2015, 7, 20, 9, 50, 1, 787000),
    u'visible': u'Y'},
    {u'Abnormal_Flag': u'',
    u'Accession_number': u'',
    u'DOB': datetime.datetime(1964, 1, 1, 0, 0),
    u'Date_Last_Obs_Normal': datetime.datetime(2015, 7, 18, 17, 36),
    u'Date_of_the_Observation': datetime.datetime(2015, 7, 18, 17, 39),
    u'Department': u'9',
    u'Encounter_Consultant_Code': u'C2754019',
    u'Encounter_Consultant_Name': u'DR. M. BERELOWITZ',
    u'Encounter_Consultant_Type': u'',
    u'Encounter_Location_Code': u'6N',
    u'Encounter_Location_Name': u'RAL 6 NORTH',
    u'Encounter_Location_Type': u'IP',
    u'Event_Date': datetime.datetime(2015, 7, 20, 9, 37),
    u'Firstname': u'TEST',
    u'MSH_Control_ID': u'18506339',
    u'OBR-5_Priority': u'N',
    u'OBR_Sequence_ID': u'1',
    u'OBR_Status': u'F',
    u'OBR_exam_code_ID': u'ANNA',
    u'OBR_exam_code_Text': u'ANTI NEURONAL ANTIBODIES',
    u'OBX_Sequence_ID': u'2',
    u'OBX_Status': u'F',
    u'OBX_exam_code_ID': u'HU',
    u'OBX_exam_code_Text': u'Neuronal Nuclear Ab1 (Hu)',
    u'OBX_id': 20363141,
    u'ORC-9_Datetime_of_Transaction': datetime.datetime(2015, 7, 20, 9, 37),
    u'Observation_date': datetime.datetime(2015, 7, 18, 17, 1),
    u'Order_Number': u'',
    u'Patient_Class': u'NHS',
    u'Patient_ID_External': u'7060976728',
    u'Patient_Number': u'20552710',
    u'Relevant_Clinical_Info': u'testing please ignore',
    u'Reported_date': datetime.datetime(2015, 7, 18, 17, 49),
    u'Request_Date': datetime.datetime(2015, 7, 18, 17, 1),
    u'Requesting_Clinician': u'',
    u'Result_ID': u'0013I245896',
    u'Result_Range': u' -',
    u'Result_Units': u'',
    u'Result_Value': u'Negative',
    u'SEX': u'F',
    u'Specimen_Site': u'^&                              ^',
    u'Surname': u'ZZZTEST',
    u'Visit_Number': u'',
    u'crs_patient_masterfile_id': None,
    u'date_inserted': datetime.datetime(2015, 7, 20, 9, 50, 1, 787000),
    u'id': 5958100,
    u'last_updated': datetime.datetime(2015, 7, 20, 9, 50, 1, 787000),
    u'visible': u'Y'},
    {u'Abnormal_Flag': u'',
    u'Accession_number': u'',
    u'DOB': datetime.datetime(1964, 1, 1, 0, 0),
    u'Date_Last_Obs_Normal': datetime.datetime(2015, 7, 18, 17, 36),
    u'Date_of_the_Observation': datetime.datetime(2015, 7, 18, 17, 39),
    u'Department': u'9',
    u'Encounter_Consultant_Code': u'C2754019',
    u'Encounter_Consultant_Name': u'DR. M. BERELOWITZ',
    u'Encounter_Consultant_Type': u'',
    u'Encounter_Location_Code': u'6N',
    u'Encounter_Location_Name': u'RAL 6 NORTH',
    u'Encounter_Location_Type': u'IP',
    u'Event_Date': datetime.datetime(2015, 7, 20, 9, 37),
    u'Firstname': u'TEST',
    u'MSH_Control_ID': u'18506339',
    u'OBR-5_Priority': u'N',
    u'OBR_Sequence_ID': u'1',
    u'OBR_Status': u'F',
    u'OBR_exam_code_ID': u'ANNA',
    u'OBR_exam_code_Text': u'ANTI NEURONAL ANTIBODIES',
    u'OBX_Sequence_ID': u'3',
    u'OBX_Status': u'F',
    u'OBX_exam_code_ID': u'RI',
    u'OBX_exam_code_Text': u'Neuronal Nuclear Ab2 (Ri)',
    u'OBX_id': 20363142,
    u'ORC-9_Datetime_of_Transaction': datetime.datetime(2015, 7, 20, 9, 37),
    u'Observation_date': datetime.datetime(2015, 7, 18, 17, 1),
    u'Order_Number': u'',
    u'Patient_Class': u'NHS',
    u'Patient_ID_External': u'7060976728',
    u'Patient_Number': u'20552710',
    u'Relevant_Clinical_Info': u'testing please ignore',
    u'Reported_date': datetime.datetime(2015, 7, 18, 17, 49),
    u'Request_Date': datetime.datetime(2015, 7, 18, 17, 1),
    u'Requesting_Clinician': u'',
    u'Result_ID': u'0013I245896',
    u'Result_Range': u' -',
    u'Result_Units': u'',
    u'Result_Value': u'Negative',
    u'SEX': u'F',
    u'Specimen_Site': u'^&                              ^',
    u'Surname': u'ZZZTEST',
    u'Visit_Number': u'',
    u'crs_patient_masterfile_id': None,
    u'date_inserted': datetime.datetime(2015, 7, 20, 9, 50, 1, 787000),
    u'id': 5958100,
    u'last_updated': datetime.datetime(2015, 7, 20, 9, 50, 1, 787000),
    u'visible': u'Y'},
    {u'Abnormal_Flag': u'',
    u'Accession_number': u'73160043383',
    u'DOB': datetime.datetime(1964, 1, 1, 0, 0),
    u'Date_Last_Obs_Normal': datetime.datetime(2016, 1, 4, 13, 15),
    u'Date_of_the_Observation': datetime.datetime(2016, 1, 4, 13, 28),
    u'Department': u'9',
    u'Encounter_Consultant_Code': u'C2754019',
    u'Encounter_Consultant_Name': u'DR. M. BERELOWITZ',
    u'Encounter_Consultant_Type': u'',
    u'Encounter_Location_Code': u'6N',
    u'Encounter_Location_Name': u'RAL 6 NORTH',
    u'Encounter_Location_Type': u'IP',
    u'Event_Date': datetime.datetime(2016, 1, 4, 13, 29),
    u'Firstname': u'TEST',
    u'MSH_Control_ID': u'21264964',
    u'OBR-5_Priority': u'N',
    u'OBR_Sequence_ID': u'2',
    u'OBR_Status': u'F',
    u'OBR_exam_code_ID': u'MYAB',
    u'OBR_exam_code_Text': u'MYOSITIS AUTOANTIBODIES',
    u'OBX_Sequence_ID': u'1',
    u'OBX_Status': u'F',
    u'OBX_exam_code_ID': u'JO2',
    u'OBX_exam_code_Text': u'Jo-1 antibodies',
    u'OBX_id': 31386917,
    u'ORC-9_Datetime_of_Transaction': datetime.datetime(2016, 1, 4, 13, 29),
    u'Observation_date': datetime.datetime(2016, 1, 4, 13, 14),
    u'Order_Number': u'',
    u'Patient_Class': u'NHS',
    u'Patient_ID_External': u'7060976728',
    u'Patient_Number': u'20552710',
    u'Relevant_Clinical_Info': u'testing please ignor',
    u'Reported_date': datetime.datetime(2016, 1, 4, 13, 16),
    u'Request_Date': datetime.datetime(2016, 1, 4, 0, 0),
    u'Requesting_Clinician': u'C4369059_Chee Ronnie',
    u'Result_ID': u'0012I258432',
    u'Result_Range': u' -',
    u'Result_Units': u'',
    u'Result_Value': u'Negative',
    u'SEX': u'F',
    u'Specimen_Site': u'^&                              ^',
    u'Surname': u'ZZZTEST',
    u'Visit_Number': u'',
    u'crs_patient_masterfile_id': None,
    u'date_inserted': datetime.datetime(2016, 1, 4, 13, 40, 7, 427000),
    u'id': 9208821,
    u'last_updated': datetime.datetime(2016, 1, 4, 13, 40, 7, 427000),
    u'visible': u'Y'},
    {u'Abnormal_Flag': u'',
    u'Accession_number': u'73160043383',
    u'DOB': datetime.datetime(1964, 1, 1, 0, 0),
    u'Date_Last_Obs_Normal': datetime.datetime(2016, 1, 4, 13, 15),
    u'Date_of_the_Observation': datetime.datetime(2016, 1, 4, 13, 28),
    u'Department': u'9',
    u'Encounter_Consultant_Code': u'C2754019',
    u'Encounter_Consultant_Name': u'DR. M. BERELOWITZ',
    u'Encounter_Consultant_Type': u'',
    u'Encounter_Location_Code': u'6N',
    u'Encounter_Location_Name': u'RAL 6 NORTH',
    u'Encounter_Location_Type': u'IP',
    u'Event_Date': datetime.datetime(2016, 1, 4, 13, 29),
    u'Firstname': u'TEST',
    u'MSH_Control_ID': u'21264964',
    u'OBR-5_Priority': u'N',
    u'OBR_Sequence_ID': u'2',
    u'OBR_Status': u'F',
    u'OBR_exam_code_ID': u'MYAB',
    u'OBR_exam_code_Text': u'MYOSITIS AUTOANTIBODIES',
    u'OBX_Sequence_ID': u'5',
    u'OBX_Status': u'F',
    u'OBX_exam_code_ID': u'KU',
    u'OBX_exam_code_Text': u'Ku antibodies',
    u'OBX_id': 31386921,
    u'ORC-9_Datetime_of_Transaction': datetime.datetime(2016, 1, 4, 13, 29),
    u'Observation_date': datetime.datetime(2016, 1, 4, 13, 14),
    u'Order_Number': u'',
    u'Patient_Class': u'NHS',
    u'Patient_ID_External': u'7060976728',
    u'Patient_Number': u'20552710',
    u'Relevant_Clinical_Info': u'testing please ignor',
    u'Reported_date': datetime.datetime(2016, 1, 4, 13, 16),
    u'Request_Date': datetime.datetime(2016, 1, 4, 0, 0),
    u'Requesting_Clinician': u'C4369059_Chee Ronnie',
    u'Result_ID': u'0012I258432',
    u'Result_Range': u' -',
    u'Result_Units': u'',
    u'Result_Value': u'Negative',
    u'SEX': u'F',
    u'Specimen_Site': u'^&                              ^',
    u'Surname': u'ZZZTEST',
    u'Visit_Number': u'',
    u'crs_patient_masterfile_id': None,
    u'date_inserted': datetime.datetime(2016, 1, 4, 13, 40, 7, 427000),
    u'id': 9208821,
    u'last_updated': datetime.datetime(2016, 1, 4, 13, 40, 7, 427000),
    u'visible': u'Y'},
    {u'Abnormal_Flag': u'',
    u'Accession_number': u'73160043383',
    u'DOB': datetime.datetime(1964, 1, 1, 0, 0),
    u'Date_Last_Obs_Normal': datetime.datetime(2016, 1, 4, 13, 15),
    u'Date_of_the_Observation': datetime.datetime(2016, 1, 4, 13, 28),
    u'Department': u'9',
    u'Encounter_Consultant_Code': u'C2754019',
    u'Encounter_Consultant_Name': u'DR. M. BERELOWITZ',
    u'Encounter_Consultant_Type': u'',
    u'Encounter_Location_Code': u'6N',
    u'Encounter_Location_Name': u'RAL 6 NORTH',
    u'Encounter_Location_Type': u'IP',
    u'Event_Date': datetime.datetime(2016, 1, 4, 13, 29),
    u'Firstname': u'TEST',
    u'MSH_Control_ID': u'21264964',
    u'OBR-5_Priority': u'N',
    u'OBR_Sequence_ID': u'2',
    u'OBR_Status': u'F',
    u'OBR_exam_code_ID': u'MYAB',
    u'OBR_exam_code_Text': u'MYOSITIS AUTOANTIBODIES',
    u'OBX_Sequence_ID': u'6',
    u'OBX_Status': u'F',
    u'OBX_exam_code_ID': u'MI2',
    u'OBX_exam_code_Text': u'Mi-2 antibodies',
    u'OBX_id': 31386922,
    u'ORC-9_Datetime_of_Transaction': datetime.datetime(2016, 1, 4, 13, 29),
    u'Observation_date': datetime.datetime(2016, 1, 4, 13, 14),
    u'Order_Number': u'',
    u'Patient_Class': u'NHS',
    u'Patient_ID_External': u'7060976728',
    u'Patient_Number': u'20552710',
    u'Relevant_Clinical_Info': u'testing please ignor',
    u'Reported_date': datetime.datetime(2016, 1, 4, 13, 16),
    u'Request_Date': datetime.datetime(2016, 1, 4, 0, 0),
    u'Requesting_Clinician': u'C4369059_Chee Ronnie',
    u'Result_ID': u'0012I258432',
    u'Result_Range': u' -',
    u'Result_Units': u'',
    u'Result_Value': u'Negative',
    u'SEX': u'F',
    u'Specimen_Site': u'^&                              ^',
    u'Surname': u'ZZZTEST',
    u'Visit_Number': u'',
    u'crs_patient_masterfile_id': None,
    u'date_inserted': datetime.datetime(2016, 1, 4, 13, 40, 7, 427000),
    u'id': 9208821,
    u'last_updated': datetime.datetime(2016, 1, 4, 13, 40, 7, 427000),
    u'visible': u'Y'},
    {u'Abnormal_Flag': u'',
    u'Accession_number': u'73160043383',
    u'DOB': datetime.datetime(1964, 1, 1, 0, 0),
    u'Date_Last_Obs_Normal': datetime.datetime(2016, 1, 4, 13, 15),
    u'Date_of_the_Observation': datetime.datetime(2016, 1, 4, 13, 28),
    u'Department': u'9',
    u'Encounter_Consultant_Code': u'C2754019',
    u'Encounter_Consultant_Name': u'DR. M. BERELOWITZ',
    u'Encounter_Consultant_Type': u'',
    u'Encounter_Location_Code': u'6N',
    u'Encounter_Location_Name': u'RAL 6 NORTH',
    u'Encounter_Location_Type': u'IP',
    u'Event_Date': datetime.datetime(2016, 1, 4, 13, 29),
    u'Firstname': u'TEST',
    u'MSH_Control_ID': u'21264964',
    u'OBR-5_Priority': u'N',
    u'OBR_Sequence_ID': u'2',
    u'OBR_Status': u'F',
    u'OBR_exam_code_ID': u'MYAB',
    u'OBR_exam_code_Text': u'MYOSITIS AUTOANTIBODIES',
    u'OBX_Sequence_ID': u'7',
    u'OBX_Status': u'F',
    u'OBX_exam_code_ID': u'PSCL',
    u'OBX_exam_code_Text': u'PmScl antibodies',
    u'OBX_id': 31386923,
    u'ORC-9_Datetime_of_Transaction': datetime.datetime(2016, 1, 4, 13, 29),
    u'Observation_date': datetime.datetime(2016, 1, 4, 13, 14),
    u'Order_Number': u'',
    u'Patient_Class': u'NHS',
    u'Patient_ID_External': u'7060976728',
    u'Patient_Number': u'20552710',
    u'Relevant_Clinical_Info': u'testing please ignor',
    u'Reported_date': datetime.datetime(2016, 1, 4, 13, 16),
    u'Request_Date': datetime.datetime(2016, 1, 4, 0, 0),
    u'Requesting_Clinician': u'C4369059_Chee Ronnie',
    u'Result_ID': u'0012I258432',
    u'Result_Range': u' -',
    u'Result_Units': u'',
    u'Result_Value': u'Negative~Testing of immunology LIMS system, please ignore~t                 hese results - HP 04/01/2016',
    u'SEX': u'F',
    u'Specimen_Site': u'^&                              ^',
    u'Surname': u'ZZZTEST',
    u'Visit_Number': u'',
    u'crs_patient_masterfile_id': None,
    u'date_inserted': datetime.datetime(2016, 1, 4, 13, 40, 7, 427000),
    u'id': 9208821,
    u'last_updated': datetime.datetime(2016, 1, 4, 13, 40, 7, 427000),
    u'visible': u'Y'},
    {u'Abnormal_Flag': u'',
    u'Accession_number': u'73160043383',
    u'DOB': datetime.datetime(1964, 1, 1, 0, 0),
    u'Date_Last_Obs_Normal': datetime.datetime(2016, 1, 4, 13, 14),
    u'Date_of_the_Observation': datetime.datetime(2016, 1, 4, 13, 28),
    u'Department': u'9',
    u'Encounter_Consultant_Code': u'C2754019',
    u'Encounter_Consultant_Name': u'DR. M. BERELOWITZ',
    u'Encounter_Consultant_Type': u'',
    u'Encounter_Location_Code': u'6N',
    u'Encounter_Location_Name': u'RAL 6 NORTH',
    u'Encounter_Location_Type': u'IP',
    u'Event_Date': datetime.datetime(2016, 1, 4, 13, 29),
    u'Firstname': u'TEST',
    u'MSH_Control_ID': u'21264964',
    u'OBR-5_Priority': u'N',
    u'OBR_Sequence_ID': u'1',
    u'OBR_Status': u'F',
    u'OBR_exam_code_ID': u'FANA',
    u'OBR_exam_code_Text': u'ANA BATTERY',
    u'OBX_Sequence_ID': u'1',
    u'OBX_Status': u'F',
    u'OBX_exam_code_ID': u'ANA',
    u'OBX_exam_code_Text': u'Anti-nuclear Antibody',
    u'OBX_id': 31386915,
    u'ORC-9_Datetime_of_Transaction': datetime.datetime(2016, 1, 4, 13, 29),
    u'Observation_date': datetime.datetime(2016, 1, 4, 13, 14),
    u'Order_Number': u'',
    u'Patient_Class': u'NHS',
    u'Patient_ID_External': u'7060976728',
    u'Patient_Number': u'20552710',
    u'Relevant_Clinical_Info': u'testing please ignor',
    u'Reported_date': datetime.datetime(2016, 1, 4, 13, 17),
    u'Request_Date': datetime.datetime(2016, 1, 4, 0, 0),
    u'Requesting_Clinician': u'C4369059_Chee Ronnie',
    u'Result_ID': u'0012I258432',
    u'Result_Range': u' -',
    u'Result_Units': u'',
    u'Result_Value': u'NEGATIVE (<1/100)',
    u'SEX': u'F',
    u'Specimen_Site': u'^&                              ^',
    u'Surname': u'ZZZTEST',
    u'Visit_Number': u'',
    u'crs_patient_masterfile_id': None,
    u'date_inserted': datetime.datetime(2016, 1, 4, 13, 40, 7, 427000),
    u'id': 9208820,
    u'last_updated': datetime.datetime(2016, 1, 4, 13, 40, 7, 427000),
    u'visible': u'Y'},
    {u'Abnormal_Flag': u'',
    u'Accession_number': u'73160043383',
    u'DOB': datetime.datetime(1964, 1, 1, 0, 0),
    u'Date_Last_Obs_Normal': datetime.datetime(2016, 1, 4, 13, 17),
    u'Date_of_the_Observation': datetime.datetime(2016, 1, 4, 13, 28),
    u'Department': u'9',
    u'Encounter_Consultant_Code': u'C2754019',
    u'Encounter_Consultant_Name': u'DR. M. BERELOWITZ',
    u'Encounter_Consultant_Type': u'',
    u'Encounter_Location_Code': u'6N',
    u'Encounter_Location_Name': u'RAL 6 NORTH',
    u'Encounter_Location_Type': u'IP',
    u'Event_Date': datetime.datetime(2016, 1, 4, 13, 29),
    u'Firstname': u'TEST',
    u'MSH_Control_ID': u'21264964',
    u'OBR-5_Priority': u'N',
    u'OBR_Sequence_ID': u'1',
    u'OBR_Status': u'F',
    u'OBR_exam_code_ID': u'FANA',
    u'OBR_exam_code_Text': u'ANA BATTERY',
    u'OBX_Sequence_ID': u'2',
    u'OBX_Status': u'F',
    u'OBX_exam_code_ID': u'FAN1',
    u'OBX_exam_code_Text': u'ANA interpretation',
    u'OBX_id': 31386916,
    u'ORC-9_Datetime_of_Transaction': datetime.datetime(2016, 1, 4, 13, 29),
    u'Observation_date': datetime.datetime(2016, 1, 4, 13, 14),
    u'Order_Number': u'',
    u'Patient_Class': u'NHS',
    u'Patient_ID_External': u'7060976728',
    u'Patient_Number': u'20552710',
    u'Relevant_Clinical_Info': u'testing please ignor',
    u'Reported_date': datetime.datetime(2016, 1, 4, 13, 17),
    u'Request_Date': datetime.datetime(2016, 1, 4, 0, 0),
    u'Requesting_Clinician': u'C4369059_Chee Ronnie',
    u'Result_ID': u'0012I258432',
    u'Result_Range': u' -',
    u'Result_Units': u'',
    u'Result_Value': u' ~By indirect immunofluorescence on HEp-2 cells. >1/100 pos                 itives~are graded + weak, ++ medium, +++ strong. >1/1000 very strong~positive.',
    u'SEX': u'F',
    u'Specimen_Site': u'^&                              ^',
    u'Surname': u'ZZZTEST',
    u'Visit_Number': u'',
    u'crs_patient_masterfile_id': None,
    u'date_inserted': datetime.datetime(2016, 1, 4, 13, 40, 7, 427000),
    u'id': 9208820,
    u'last_updated': datetime.datetime(2016, 1, 4, 13, 40, 7, 427000),
    u'visible': u'Y'}
]
